### ISSUE TITLE
Ironsidesec - Users can front-run the price increase of supported LSTs/LRTs (stETH) tokens in order to capture MEV value.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#140]
Ironsidesec

Medium

# Users can front-run the price increase of supported LSTs/LRTs (stETH) tokens in order to capture MEV value.

## Summary
Issue is minting the token when staking them is. The `tvl()` call  determinig the LP price is vulnerable here.

**Root cause**: lacking deposit queue of minting the LP tokens in exchange of staking the token. Imagine if deposit queue is there, the MEV bots can never extract the value because the share price calculation is done when minting but not while deposit request. So minting 1 block after the deposit request will eliminate this issue.

**Similar Isuue** : https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/66
**Likelihood** : easy : https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/66#issuecomment-2139602846

## Vulnerability Detail
stETH is subject to an instant increase in their shares value (or shares balance), mainly due to beacon chain validator rewards.

Mellow vaults allow users to deposit ETH  -> wstETH in the protocol in exchange for LP tokens instantly, without being subject to a deposit queue. This allows an attacker to frontrun a price/balance increase by doing the following:

1. Monitor the supported LSTs/LRTs protocols and the beacon chain for an imminent share price/balance increase.
2. Frontrun the share price/balance increase by depositing ETH in the relative LST/LRT vault via `vault.deposit` or through `swapper` util to convert ETH into wstETH and then `vault.deposit` which will deposit those into the bond/strategy depending on that vault, in exchange for LP token minted on L407 below.
3. Wait for the share price increase to take effect, which will increase the TVL of the vault, the stETH value in oracle will increase its price so is its TVL and the LP token price also increase. 
4. Then backrun and register a withdrawal to complete this MEV value extraction of LP share price change.

This allows an attacker to capture profit while being subject to the risks of staking for only a few hours till processing the withdrawal requests.

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L338

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L367
```solidity
2024-06-mellow/mellow-lrt/src/Vault.sol


309:     function deposit(
310:         address to,
314:     )
319:     {
320:         if (configurator.isDepositLocked()) revert Forbidden();
... SNIP ...
373: 
374:  >>>    lpAmount = _processLpAmount(to, depositValue, totalValue, minLpAmount);
375:         emit Deposit(to, actualAmounts, lpAmount);
376:         address callback = configurator.depositCallback();
377:         if (callback == address(0)) return (actualAmounts, lpAmount);
378:  >>>    IDepositCallback(callback).depositCallback(actualAmounts, lpAmount);
379:         emit DepositCallback(callback, actualAmounts, lpAmount);
380:     }
381: 

386:     function _processLpAmount(
387:         address to,
... SNIP ...
390:         uint256 minLpAmount
391:     ) private returns (uint256 lpAmount) {
... SNIP ...
404: 
405:         if (lpAmount + totalSupply > configurator.maximalTotalSupply())
406:             revert LimitOverflow();
407:   >>>   _mint(to, lpAmount);
408:     }

```

## Impact
An attacker can frontrun an price/balance increase of a supported LSD/LRT token (stETH) in order to capture value, which translates into honest stakers earning less yeild than they should.

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L338

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L367

## Tool used
Manual Review

## Recommendation

Introduce a deposit queue with delay like register withdrawal and process withdrawal, this prevents an attacker from frontrunning price increases for profit.

**Comment by IronsideSec** [comment]
Escalate
All LST/LRT based protocols have the deposit queues, even perp trading ones like GMX/perpetual protocol. The deposit queue has to be 1. request deposit, 2. execute deposit.
That is how MEV is combatted. And the withdrawal process here is well implemented, but deposit isn't.

MEV extraction at this easy [likelihood](https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/66#issuecomment-2139602846) should atleast be a medium.

**Comment by sherlock-admin3** [comment]
> Escalate
> All LST/LRT based protocols have the deposit queues, even perp trading ones like GMX/perpetual protocol. The deposit queue has to be 1. request deposit, 2. execute deposit.
> That is how MEV is combatted. And the withdrawal process here is well implemented, but deposit isn't.
> 
> MEV extraction at this easy [likelihood](https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/66#issuecomment-2139602846) should atleast be a medium.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and validate with medium severity. @z3s @IronsideSec are there any duplicates?

**Comment by 10xhash** [comment]
> Agree with the escalation, planning to accept and validate with medium severity. @z3s @IronsideSec are there any duplicates?

In order to extract value, the withdrawal have to be completed which can only be done when the admin invokes the processWithdrawals function (expected frequency of 1-7days) and also the user is required to pay a fee (both these are kept to counter this) 

Because LST's fundamentally gain in price at the time of rebalance doesn't make the increase in price anywhere outrageous to break the assumptions made with oracle updates of any other token. If we take the LST to even reward 10% / yr, it comes down to an increase of ~0.02739726% a day

**Comment by IronsideSec** [comment]
>are there any duplicates?

@WangSecurity  #40 is (root cause and recommendation fix matches), #11 

>In order to extract value, the withdrawal have to be completed which can only be done when the admin invokes the processWithdrawals function (expected frequency of 1-7days) and also the user is required to pay a fee (both these are kept to counter this)

@10xhash  Even if you enforce delay, there are bots who can wait for the profits. And  anyone with enough funds can deposit half of the vault will make enough profits at (~0.02739726% a day) even after fees if its not greater than (~0.02739726% ).

currently [withdrawal fee is 0](https://etherscan.io/address/0xe6180599432767081beA7deB76057Ce5883e73Be#readContract#F24) (may be vault manager's choice or turned on when withdrawals are processed ). The emergency withdraw doesn't charge fee but it will have more delay than request withdraw. So choose that if more profit is needed.

This is a permissionless protcol, so  cant rely on just withdrawal delay and fees to solve mev because those vault managers with low delay, low fees for their vault are prone to this attack. Deposit with 2 step process solves completely irrespective of delay/fees.  This is medium to low likelihood, but still a profitable high impact.

**Comment by WangSecurity** [comment]
@IronsideSec could you also give a bit explanation, you link to the Mellow's Vault and which exactly?

**Comment by IronsideSec** [comment]
@WangSecurity  Linked  one [Steakhouse Resteaking Vault (steakLRT)](https://etherscan.io/token/0xBEEF69Ac7870777598A04B2bd4771c71212E6aBc) with $194M tvl

<img width="1131" alt="image" src="https://github.com/user-attachments/assets/1343d899-3372-4662-ac25-1e1fb3fd408b">

Hash says that with withdrawal fees and delay its not profitable to make $$ out of that daily reward update. But I say, the bot can wait  and there will be vaults without fees/low fees. And targetting them is profitable. 

Also mellow is permissionless LRT vault managemant protcol, so relying only on withdrawal delay + fees to counter MEV  is an issue becasue those parameters are set by their vault managers. If withdrawal fees is lower than daily reward update apr, then MEV is profitable, eventhough withdraw delay will discorage some meb vots from participating. So this is still medium likelihood

So, create deposit queue to remove this MEV issue so that no matter the withdraw delay/fees, MEV is not possible.

**Comment by WangSecurity** [comment]
I agree that the delay can be either long or short depending on the vault, as well as the withdrawal fee which can be either high or short. I still believe it's a valid issue, since it not only allows for the attacker to capture value but also leads to other depositors getting less value.

Planning to accept the escalation and validate with medium severity, since the attacker has to wait for the withdrawal request, which can easily make the attack unprofitable (i.e. the LST/LRT price falls in the meantime or get arbitraged). The duplicates are #11. I believe #40 is not a valid duplicate, since the attack is not possible due to the withdrawal queue.

**Comment by 0xHuntoor** [comment]
@WangSecurity sorry, but this report is subject to withdrawal queue too, and you say that being subject to withdrawal queue may make the attack unprofitable

**Comment by WangSecurity** [comment]
Yep, I acknowledged that it's subject to withdrawal queue (excuse me, it was a bit vague, but that's what I meant when said the attacker would have to wait for the withdrawal request).

I believe it decreases the severity, but doesn't invalidate the report. The decision remains the same, planning to accept the escalation and validate with medium severity. @z3s @IronsideSec are there any duplicates?

**Comment by IronsideSec** [comment]
#11 and this ( #140 )

**Comment by 10xhash** [comment]
> Yep, I acknowledged that it's subject to withdrawal queue (excuse me, it was a bit vague, but that's what I meant when said the attacker would have to wait for the withdrawal request).
> 
> I believe it decreases the severity, but doesn't invalidate the report. The decision remains the same, planning to accept the escalation and validate with medium severity. @z3s @IronsideSec are there any duplicates?

In addition to the increase itself (ie. inflated 10% yrly coming to 0.02% day) not being enough to trigger an oracle update, the withdrawal delay means the user is exposed to the associated risks too. And the fees as I already mentioned is also kept to combat the free conversion b/w assets. 
> since it not only allows for the attacker to capture value but also leads to other depositors getting less value 

Can you please request for a POC supporting this statement that shows any considerable amount of value capture done through this method?
It must be possible for any user doing this, to front run the share price update of the lido contract itself directly (ie. not through mellow) inorder to gain this much value
And since a price update should be predictable before a period of 1 block, what problem does the deposit queue solve?

**Comment by 0x3b33** [comment]
@WangSecurity I think this one -- [89](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/89) -- can be considered a duplicate. It uses the same method, however in reverse, where it targets LST slashing in order to transfer some of the impact from the user to Mellow.

The mentioned issue shows how using this method during an LST slashing event the user can lower the vault share value and capture some of it.

**Comment by WangSecurity** [comment]
Firstly, as I understand, the price increase can be larger than 0.02% due to validator rewards, but please correct me if it's wrong. I agree fees and withdrawal delay act as a constraint here.

> In addition to the increase itself (ie. inflated 10% yrly coming to 0.02% day) not being enough to trigger an oracle update, the withdrawal delay means the user is exposed to the associated risks too. And the fees as I already mentioned is also kept to combat the free conversion b/w assets.

Secondly, @IronsideSec could you come up with a realistic numerical scenario to measure the loss and captured value? Maybe I indeed miss something here.

> Can you please request for a POC supporting this statement that shows any considerable amount of value capture done through this method?

Thirdly, I believe the deposit queue allows to solve it since even a 1-day queue wouldn't allow the attacker to front-run the share price increase and get value from it.

> And since a price update should be predictable before a period of 1 block, what problem does the deposit queue solve?

About duplicates, will reflect on it later.

**Comment by IronsideSec** [comment]
>the price increase can be larger than 0.02% due to validator rewards, but please correct me if it's wrong. I agree fees and withdrawal delay act as a constraint here.

- There can be days without rebase too. Link : https://x.com/LidoFinance/status/1590353781434503171
- Maximum limit can be at ~ 0.075 %, . Likelihood of > 0.02% is aalso above low likelihood. 

Message link : https://discord.com/channels/761182643269795850/774278679379443722/1235607455690526770

<img width="743" alt="image" src="https://github.com/user-attachments/assets/ba8b6a40-8f5f-4f97-9704-3a6aa5adda4c">

.
> could you come up with a realistic numerical scenario to measure the loss and captured value? Maybe I indeed miss something here.

if there is a day with 0.05% rebase, then on a 1000 eth vault, tvl would increase by 0.05% in price, so MEVing this will take lot of capital  to profit off and subject to fee + delay, via deposit => register withdrawal => process withdrawal.

But there are [vaults with enough tokens to do emergency withdrawal which has no fee](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L403-L409), but con is still withdraw delay is there and high capital needed. 

So, this MEV is not profitable on vaults with withdrawal delay + fees. If there's no delay, then extraction is high impact. Since its a permissionless LRT vault protocol, if vault manager has zero delay on emergency withdrawal + enough non-underlying tokens, then profitable. But looks very low likelihhod.

**Comment by WangSecurity** [comment]
Thank you for that clarification. I agree that there can be vaults without a fee and it's a viable scenario, but still I believe withdrawal delay is a significant constraint and there can't be no delay on emergency withdrawals, since the user has to first create a withdrawal request, then can only make an emergency withdrawal if the admin doesn't process regular withdrawals.

Additionally, the profit being extremely limited, hence, the value that honest depositors wouldn't receive is extremely low. On vault with 1000 ETH and TVL increase of 0.05%, it would lead to an increase of 0.5 ETH and the attacker would need a significant capital to capture a reasonable part of it.

Hence, taking both considerations above together, I would agree it's indeed low severity. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ironsidesec](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/140/#issuecomment-2232341020): rejected
