### ISSUE TITLE
cjm00n - Missing value check in `commitMaximalTotalSupply` function

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#142]
cjm00n

Medium

# Missing value check in `commitMaximalTotalSupply` function

## Summary

The vulnerability is attributable to the absence of a validation mechanism that ensures the newly staged maximal total supply is greater than or equal to the current total supply when it's time to commit this value, post the staging delay period.

## Vulnerability Detail

- The `stageMaximalTotalSupply` function correctly checks that the newly proposed `maximalTotalSupply_` cannot be less than the current total supply of the vault (`IVault(vault).totalSupply()`). If this condition is not met, the operation reverts.
- After staging, there is a delay (`_maximalTotalSupplyDelay`) before the new maximal total supply can be committed to ensure time for review and possibly, for objections to be raised.
- The issue here is that the total supply (`IVault(vault).totalSupply()`) could increase during the delay period, surpassing the staged maximal total supply to be committed when call `commitMaximalTotalSupply`.

## Impact

MaximalTotalSupply is wrongly set to a small value

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/VaultConfigurator.sol#L200-L211

```solidity
    function stageMaximalTotalSupply(
        uint256 maximalTotalSupply_
    ) external onlyAdmin nonReentrant {
        if (maximalTotalSupply_ < IVault(vault).totalSupply())
            revert InvalidTotalSupply();
        _stage(_maximalTotalSupply, maximalTotalSupply_);
    }

    /// @inheritdoc IVaultConfigurator
    function commitMaximalTotalSupply() external onlyAdmin nonReentrant {
        _commit(_maximalTotalSupply, _maximalTotalSupplyDelay);
    }
```

## Tool used

Manual Review

## Recommendation

Add check in `commitMaximalTotalSupply` like `stageMaximalTotalSupply`

**Comment by 0xklapouchy** [comment]
@z3s 

This process cannot be executed in a single transaction due to a required delay between the stage and commit actions. In the current deployment scripts, this delay is set to one day.

Consider the following scenario:

1. The maximum total supply is set to 4,000, with a current total supply of 2,999.
2. The protocol decides to reduce the maximum total supply to 3,000.
3. The stageMaximalTotalSupply() function is called.
4. During the one-day delay, the total supply increases to 3,001.
5. When commitMaximalTotalSupply() is called, the maximum total supply is set to 3,000, which is now less than the current total supply.

The protocol's intention, as evident from the code, is to validate that the maximum total supply is greater than the total supply. However, this validation is placed incorrectly, rendering the functionality broken.

This is a valid issue.
