### ISSUE TITLE
den_sosnovskyi - `Vault::_calculateTvl` can be DOS attacked

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#152]
den_sosnovskyi

Medium

# `Vault::_calculateTvl` can be DOS attacked

## Summary
`Vault::_calculateTvl` count tvl from all modules and can be attacked by manipulating `negativeAmounts` balance.

## Vulnerability Detail
`Vault::_calculateTvl` will revert if `negativeAmounts` is > than `amount`. If the current module has same tokens for isDebt false Data, and isDebt true Data, this check will be checked `if (amounts[i] < negativeAmounts[i]) revert InvalidState();`. Because some module amounts are counted using ERC20 balanceOf function, attacker can send negativeAmounts token to the vault to make it bigger than amount. If the difference between those amount is not big, it can be very cheap for the attacker

## Impact
Can block calculate tvl functionality

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L105-L107
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/modules/symbiotic/DefaultBondTvlModule.sol#L33-L36

## Tool used

Manual Review

## Recommendation
do not use ERC20 balanceOf function to count tvl, instead use variables

**Comment by recursiveEth** [comment]
Escalate
same issue as #52, Vault::_calculateTvl count tvl from all modules and can be attacked by manipulating negativeAmounts balance, resulting in DOS.

**Comment by sherlock-admin3** [comment]
> Escalate
> same issue as #52, Vault::_calculateTvl count tvl from all modules and can be attacked by manipulating negativeAmounts balance, resulting in DOS.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0x3b33** [comment]
Escalate

This issue is not a duplicate of issue 52 (https://github.com/sherlock-audit/2024-06-mellow-judging/issues/52) and thus is invalid.

It's invalid based on the assumptions and method of the "attack". The watson stated that "modules can be attacked by manipulating negativeAmounts balance". This is not possible because the only module that can return `isDebt == true` is `ManagedTvlModule`. No other module, especially `ERC20TvlModule`, can return `isDebt == true`. Therefore, the attack described by this watson is impossible to execute, meaning there is no actual attack path in this report.

The issue doesn't clearly state the damage that can be achieved, and its proposed solution will not fix the actual issue.
> do not use ERC20 balanceOf function to count TVL; instead, use variables.

The report above should not be marked as a duplicate of 52, as it does not address the actual vulnerability.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue is not a duplicate of issue 52 (https://github.com/sherlock-audit/2024-06-mellow-judging/issues/52) and thus is invalid.
> 
> It's invalid based on the assumptions and method of the "attack". The watson stated that "modules can be attacked by manipulating negativeAmounts balance". This is not possible because the only module that can return `isDebt == true` is `ManagedTvlModule`. No other module, especially `ERC20TvlModule`, can return `isDebt == true`. Therefore, the attack described by this watson is impossible to execute, meaning there is no actual attack path in this report.
> 
> The issue doesn't clearly state the damage that can be achieved, and its proposed solution will not fix the actual issue.
> > do not use ERC20 balanceOf function to count TVL; instead, use variables.
> 
> The report above should not be marked as a duplicate of 52, as it does not address the actual vulnerability.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
The @recursiveEth escalation will be rejected either way, since this issue is already a duplicate of #52 and #52 is also escalated, so this escalation doesn't add any value.

About @0x3b33 escalation, agree it's not a duplicate since it doesn't show a valid attack/vulnerability path and a sufficient proof of Medium severity. It's dependant on #52 being valid in the end, if it is, then this escalation will be accepted and this report will be deduplicated. If #52 remains invalid, this escalation will also be rejected, since it wouldn't affect reward distribution.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/152/#issuecomment-2228769409): accepted
- [recursiveEth](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/152/#issuecomment-2228671948): rejected
