### ISSUE TITLE
eeyore - Incorrect TVL/Value calculations as token amounts are not normalized for tokens with decimals !=18

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#160]
eeyore

High

# Incorrect TVL/Value calculations as token amounts are not normalized for tokens with decimals !=18

## Summary

The `priceX96` returned from the price oracle is intended to be used only with tokens that have 18 decimals. If USDC or USDT is used as underlying tokens, their amounts will not be normalized in TVL calculations, resulting in them being undervalued by a factor of 10^12.

## Vulnerability Detail

During the deposit or withdrawal process, the TVL of the vault and value of the deposit is calculated to determine the LP values to be minted or burned. If new tokens are added as underlying tokens that do not have 18 decimals, their values can be undervalued or overvalued by the system.

The lack of amount normalization can be seen in this example:

1. The vault is initially set to accept only WSTETH as the underlying token, and 40 WSTETH has been deposited so far.
2. A new underlying token, USDC, is added with the price oracle correctly set to the USDC/ETH price feed.
3. TVL is nominated in WETH, lets assume 1 WETH priced at approximately 3000 USDC in the market.
4. Alice deposits 1 WSTETH and 3000 USDC.
5. The correct price is returned from the USDC oracle but is designated for tokens with 18 decimals.
6. The 3000 USDC deposit is valued only as 0.000000000001 ETH.
7. Alice's LP tokens are minted at only about half of the real token value added.

## Impact

Incorrect TVL calculations can lead to user funds being lost or the vault being drained, especially when deposit and withdrawal token ratios are changed in a way that is unfavorable to the protocol.

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L326
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L335
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L529

## Tool used

Manual Review

## Recommendation

Normalize amounts used in TVL/value calculations to 18 decimals (do not normalize `priceX96` itself as it is correctly used in `ratiosX96Value` calculations).

For example:
```diff
        for (uint256 i = 0; i < tokens.length; i++) {
            uint256 priceX96 = priceOracle.priceX96(address(this), tokens[i]);
            totalValue += totalAmounts[i] == 0
                ? 0
-                : FullMath.mulDivRoundingUp(totalAmounts[i], priceX96, Q96);
+                : FullMath.mulDivRoundingUp(totalAmounts[i] * 10**(18 - tokens[i].decimals()), priceX96, Q96);
            if (ratiosX96[i] == 0) continue;
            uint256 amount = FullMath.mulDiv(ratioX96, ratiosX96[i], Q96);
            IERC20(tokens[i]).safeTransferFrom(
                msg.sender,
                address(this),
                amount
            );
            actualAmounts[i] = amount;
-           depositValue += FullMath.mulDiv(amount, priceX96, Q96);
+           depositValue += FullMath.mulDiv(amount * 10**(18 - tokens[i].decimals()), priceX96, Q96);
        }
```

**Comment by 0xklapouchy** [comment]
@z3s 

This issue is not about priceX96() function of the ChainlinkOracle.sol, this issue assume that price is returned correctly.

All the duplicates indicating issue in ChainlinkOracle are not duplicates of this issue.

This issue is about missing normalization of the amounts in the Vault contract.

**Comment by IWildSniperI** [comment]
@z3s 
![image](https://github.com/user-attachments/assets/855bd59a-372e-45a7-bb2a-a309f0e66fdc)
![image](https://github.com/user-attachments/assets/9d1a4ae5-eac8-441c-b44e-f2578b8e4485)
scope was updated

**Comment by Al-Qa-qa** [comment]
Escalate.

On @IWildSniperI behalf

**Comment by sherlock-admin3** [comment]
> Escalate.
> 
> On @IWildSniperI behalf

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by z3s** [comment]
I knew the scope was updated, and my reason for invalidating this submission was because it was mentioned in the known issues in the README. Therefore, the Protocol team are aware of this problem.
I think it's better to let the internal judge decide.

**Comment by 0xklapouchy** [comment]
@z3s 

I think you are right, after rechecking my issue, the fix done in `priceX96()` resolve this problem of missing normalization in the Vault, so at the end it was a Know issue.

There is a problem with ratiosX96 in the code and working with tokens that don't have same decimals is nightmer, as calculations for them are not as easy as protocol thinks:

2^96 / 2
2^96 / 2

Is not valid calculation for ratio 50/50

Ratios needs to be normalized for proper use, in case of for example [ETH, USDC]

To calculate the ratiosX96 for them we need to normalize for each of them:

Adjusted Ratios per decimals:

Adjusted ETH: 0.5 * 10^18 
Adjusted USDC: 0.5 * 10^6

Total Adjusted Ratios = 0.5 * 10^18  + 0.5 * 10^6

Normalize Ratio ETH = 0.5 * 10^18 * 2^96  / (0.5 * 10^18  + 0.5 * 10^6)
Normalize Ratio USDC = 0.5 * 10^6 * 2^96 / (0.5 * 10^18  + 0.5 * 10^6)

`Adjusted * 2^96 / Total Adjusted Ratios`

As those setting are provided by the admin, the calculations will hold in the contract, but protocol needs to be aware that the final ratios will be like this:

ETH X96 : `79228162514185109431029765226`
USDC X96: `79228162514185109`

50/50 ETH,USDC ratiosX96.

**Comment by IWildSniperI** [comment]
reasons for escalating this
> In src/oracles/ChainlinkOracle.sol, the priceX96 function does not take into account IERC20(base).decimals() and IERC20(token).decimals() when converting. For the current deployment, this is not a problem because the system operates with tokens from the set [weth, wsteth, steth].

scope gets updated and now the system works with different decimals tokens -> now this is not a problem like the readMe says?

or is it a problem now?

cause we in sherlock work with the code provided

**Comment by blckhv** [comment]
It's common sense that when the README was updated this automatically became a valid issue since USDC and USDT were introduced:
> For the current deployment, this is not a problem because the system operates with tokens from the set [weth, wsteth, steth].

This sentence is not true anymore.

**Comment by InfectedIsm** [comment]
Doesn't `"For the current deployment, this is not a problem because the system operates with tokens from the set [weth, wsteth, steth]"` imply then that it is a known issue that there was a problem for tokens outside of the set, i.e USDC/USDT?
Especially because they say before `"does not take into account IERC20(base).decimals() and IERC20(token).decimals() when converting"` showing that they knew the issue is about decimals

**Comment by WangSecurity** [comment]
To clarify one part, this issue arise only when there are two underlying tokens with different decimals and there wouldn't be any issue if the underlying token is only USDC or only USDT?

**Comment by IlIlHunterlIlI** [comment]
@WangSecurity yes.

**Comment by 0xklapouchy** [comment]
@WangSecurity 

And no. 

Depends what is set as baseToken in the ChainlinkOracle.sol

If baseToken is USDC, then will work.
If baseToken will be WETH, then not working.

**Comment by 0xklapouchy** [comment]
Overall, it holds (if configured correctly for only one token and not using real Chainlink oracles), but everything is held together with duct tape and baling wire. The entire `addToken()` function should be removed, and the system should only work with one underlying token.

**Comment by 0xklapouchy** [comment]
However, it seems we are now searching for edge cases where the system works, while in most cases, it will not work when considering its possibilities.

**Comment by WangSecurity** [comment]
To clarify one more time, excuse me, just want to be sure, if the underlying decimals == base decimals, then it works correctly (e.g. USDC and USDT) but if `underlying decimals != base decimals` it works incorrectly (e.g. WETH and USDC), correct?

**Comment by IWildSniperI** [comment]
@WangSecurity 

in `ChainlinkOracle` we neutralize Decimals difference between base and underlying but we neutralize the Oracle decimals not the ERC20 decimals, cause different oracles may have different decimals

```solidity
    function priceX96(
        address vault,
        address token
    ) external view returns (uint256 priceX96_) {
        priceX96_ = FullMath.mulDiv(
            tokenPrice * 10 ** baseDecimals, <<@ Oracle decimals not the ERC20 decimals
            Q96,
            baseTokenPrice * 10 ** decimals <<@ Oracle decimals not the ERC20 decimals
        );
    }
```

> To clarify one more time, excuse me, just want to be sure, if the underlying decimals == base decimals, then it works correctly (e.g. USDC and USDT) but if underlying decimals != base decimals it works incorrectly (e.g. WETH and USDC), correct?

yes

**Comment by IWildSniperI** [comment]
a small add to my above statement is that in the deployment script we have `WETH` as baseToken

and from the scope update we have USDC,USDT as underlying

so we have a working example of bug with the inputs of the sponsor

**Comment by WangSecurity** [comment]
> a small add to my above statement is that in the deployment script we have `WETH` as baseToken
> 
> and from the scope update we have USDC,USDT as underlying
> 
> so we have a working example of bug with the inputs of the sponsor

But USDC and USDT are not underlying tokens in deployment script? And in deployment script which token is the underlying?

**Comment by IWildSniperI** [comment]
> But USDC and USDT are not underlying tokens in deployment script?

Yes cause they were considered later after scope update

> And in deployment script which token is the underlying?

wstETH

**Comment by InfectedIsm** [comment]
Just want to add to the discussion that the vulnerability/impact described [after the escalation](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/160#issuecomment-2229397738) wasn't present in the initial submission. Also, as stated by the initial author (@0xklapouchy) in this comment:
1) He agree with the fact that the original issue is known issue from the readme:
    >"the fix done in priceX96() resolve this problem of missing normalization in the Vault, so at the end it was a Known issue."
2) the updated issue described after the escalation exists only if admin do not correctly set ratios for tokens with different decimals: 
    >"As those setting are provided by the admin, the calculations will hold in the contract"

Also, the issue rely on the fact that the admin will use tokens with different decimals in a same vault, although they know that (readme):
> In src/oracles/ChainlinkOracle.sol, the priceX96 function does not take into account IERC20(base).decimals() and IERC20(token).decimals() when converting. For the current deployment, this is not a problem because the system operates with tokens from the set [weth, wsteth, steth].

Which basically means: if only underlying are [weth, wsteth, steth] this is not an issue (which is true), but if there are other tokens from this set, we know that there will be an issue because of decimals.

**Comment by ADK0010** [comment]
Actually , I have some points to explain on this issue . Thanks @InfectedIsm for your insights . 
1) Firstly the issue pertains due to decimal issue with `priceX96` & also due to the `amounts` (which is used without decimal scaling) . So all issues that mention both `priceX96` & `amounts` should be considered . 
2) Secondly , the issue is not about admin setting wrong ratios , even with right ratios as the amount variables are not scaled , it will cause issues in deposit and withdraw of the Vault.sol . 
And just for clarification , let's use an example provided by sponsor in discord : https://discord.com/channels/812037309376495636/1252276613417013353/1254898899852857446
Here we see the ratiosX96 is set for WstEth & Usdc correctly but the problem is with the unscaled amounts which is used as 20x2^96 for Usdc & 10x2^96 for wstEth. 
```
    ratioX96 = min(ratioX96, 10 * 2^96 / (2^96 / 4)) (which is also equal to min(ratioX96, 40))
    ratioX96 = min(ratioX96, 20 * 2^96 / (2^96 * 3 / 4)) (which is also equal to min(ratioX96, 26))
```    
Here we can clearly see the Developer has assumed that decimals of amounts of Usdc & WstEth are equal , thereby not even considering there decimals - but actually the amount of Usdc & WstEth provided by the User will have 6 & 18 decimals respectively . 
This is code part of the same scaling problem in Vault.sol - 
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L310C1-L314C60

Also this issue is seen while withdrawing Usdc too , which will cause revert always . So I believe this issue to be a High severity issue . Correct me if I'm wrong in any of my statements .

**Comment by IWildSniperI** [comment]
for heads up on definitions 
![image](https://github.com/user-attachments/assets/c879658f-774e-40b7-896f-897c7e9e1dce)
so assuming that underlying will be also `BaseToken` is being over optimistic to get a working way of the protocol

i know the rules that if there is only 1 path for the protocol to work good then this would be invalid

but assumption is that underlying is underlying not more or less 
- used for deposits and withdrawals

and i don't know if this is helpful, but this is solved under pull request as sherlock Fix [here](https://github.com/mellow-finance/mellow-lrt/pull/44/files#:~:text=vault%2C-,vault%2C,%7D,-9%20changes%3A%204) from sponsor

**Comment by WangSecurity** [comment]
In this case, I would still agree with the lead judge that it's a known issue that tokens with different decimals would cause issues, based on the statement in the README.

With that, I agree that it should remain as it is, planning to reject the escalation and leave the issue as it is.

**Comment by IWildSniperI** [comment]
Known but ignored cause there was no usdc, now usdc gets scoped then we still ignore it?

**Comment by ADK0010** [comment]
@WangSecurity Please check my comment above for details - https://github.com/sherlock-audit/2024-06-mellow-judging/issues/160#issuecomment-2241903007

Known issue is about scaling of `priceX96`, but scaling is also needed for amounts variable , which was forgotten even in the example given by sponsor in discord as can be seen in my comment above . I don't know what @IWildSniperI is saying but I don't think the scaling issue caused by disproportionate decimals of `amounts` in deposit & withdraw functions were known issue . So I believe the issues mentioning both `priceX96` and `amounts` or just `amounts` should be considered valid & the issues mentioning just `priceX96` should be considered known issue .

**Comment by ADK0010** [comment]
Also to include as example , issues #86 & #88 seems valid but issue #105 from same author seems like known issue mentioned by Lead Judge. @WangSecurity please do look into my above 2 comments before invalidating this family of report.

**Comment by WangSecurity** [comment]
Thank you for these examples @ADK0010 but in that case the questions about admin set variables has no limitations and in that case we should assume the admins will use values that won't cause any issues. In that case, as I understand, using tokens with the same decimals will not cause any issues, e.g. USDC/USDT or WETH/wstETH. Moreover, I don't see that current live vaults on Mellow have tokens with different decimals in the same vault. Hence, this should remain low and unrewarded based on the rules:

> (External) Admin trust assumptions: When a function is access restricted, only values for specific function variables mentioned in the README can be taken into account when identifying an attack path.
If no values are provided, the (external) admin is trusted to use values that will not cause any issues.
Note: if the attack path is possible with any possible value, it will be a valid issue.
Exception: It will be a valid issue if the attack path is based on a value currently live on the network to which the protocol will be deployed.

The decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by 10xhash** [comment]
> Thank you for these examples @ADK0010 but in that case the questions about admin set variables has no limitations and in that case we should assume the admins will use values that won't cause any issues. In that case, as I understand, using tokens with the same decimals will not cause any issues, e.g. USDC/USDT or WETH/wstETH. Moreover, I don't see that current live vaults on Mellow have tokens with different decimals in the same vault. Hence, this should remain low and unrewarded based on the rules:
> 
> > (External) Admin trust assumptions: When a function is access restricted, only values for specific function variables mentioned in the README can be taken into account when identifying an attack path.
> > If no values are provided, the (external) admin is trusted to use values that will not cause any issues.
> > Note: if the attack path is possible with any possible value, it will be a valid issue.
> > Exception: It will be a valid issue if the attack path is based on a value currently live on the network to which the protocol will be deployed.
> 
> The decision remains the same, planning to reject the escalation and leave the issue as it is.

Shouldn't the same logic be applied to the judgement of https://github.com/sherlock-audit/2024-06-mellow-judging/issues/52 too. Where the issue only occurs if the admin sets the debt (artificially reducing the tvl with no associated logic) to high percentages of the token balance

**Comment by WangSecurity** [comment]
Yes, that’s what I’m considering now and admit that my decision may be incorrect on #52 and I may change it. Let’s keep the discussion about #52 on it and I’ll get back to it.

**Comment by ADK0010** [comment]
@WangSecurity you said tokens with different decimals might not be used together . But the discord link provided in this message - https://github.com/sherlock-audit/2024-06-mellow-judging/issues/160#issuecomment-2241903007
says something else . Sponsor himself gave an example of using two tokens with different decimals , after the change was done to the scope . Now how else should we know whether the protocol plans to use 2 tokens with different decimals together or not . And obviously the deployed ones doesn't have 2 tokens with different decimals as it was decided midway through the audit to add these to scope . Correct me if I'm wrong .

**Comment by IWildSniperI** [comment]
Have you considered the fact of underlying != Base (tokens) sir?

And we have known the intent of underlying to be WETH(18 Decimals) from deployment script?

**Comment by ADK0010** [comment]
Also @WangSecurity , you said admin can give whatever value for ratiosX6 to adjust the scaling . Look at this , in the deposit function , ratioX96 is in the [denominator](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L313C1-L314C60) , so to scale it ratioX96 should be denominated by 10**12 . But then comes this condition in [ManagedRatiosOracle.sol](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/oracles/ManagedRatiosOracle.sol#L30C9-L30C26) , which makes it impossible to do scaling by adjusting ratioX96 . I still believe it is a High severity issue , as it causes complete withdrawal DOS & scaling issues while depositing . Now I'll leave to you to decide upon it .

**Comment by WangSecurity** [comment]
@ADK0010 thank you for this information and I see a scenario of how this vulnerability (not the report) can be valid, considering also the fact that WETH is used as the base token in the deployment script, so the scenario of USDC as underlying and WETH as base is valid.

But, this report mentions the scenario with 2 underlying tokens with different decimals, which I believe would be invalid, based on the rule I quoted in the previous comment. But, I will reflect on other reports that were mentioned above and are duplicates of this one.

**Comment by ADK0010** [comment]
@WangSecurity I think we are again going round and coming back to same place . Anyway , Weth is used as base token for Chainlink Oracle contract , so priceX96 will be calculated in terms of Weth as can be seen here - https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/oracles/ChainlinkOracle.sol#L94C2-L99C6
Also this meesage by sponsor - https://discord.com/channels/812037309376495636/1252276613417013353/1254927894707437700

But in the example provided by sponsor here - https://discord.com/channels/812037309376495636/1252276613417013353/1254898899852857446

He is using two underlying tokens with different decimals , Weth & Usdc is considered as underlying tokens and is possible as per here - https://discord.com/channels/812037309376495636/1252276613417013353/1254897219790831747

In the Vault the base token is not Weth or Wsteth or any other token , instead it is the bond token from the Symbiotic - https://discord.com/channels/812037309376495636/1252276613417013353/1254928937327263834

Actually it doesn't matter whatever the base token is , if two underlying tokens with different decimals are used it will cause problems . In discord the sponsor used the example and it was denoting 2 underlying tokens only .

**Comment by WangSecurity** [comment]
Yep, there's a misunderstanding, let me re-iterate how I see your comments, so you can correct me. You saying that it's possible there can be vaults with underlying tokens with different decimals (e.g. wETH/USDC). The evidence is the sponsor's message in Discord. Hence, we should consider this scenario. If I understood your message correctly, then here's my answer:

> He is using two underlying tokens with different decimals, Weth & Usdc is considered as underlying tokens and is possible as per here - https://discord.com/channels/812037309376495636/1252276613417013353/1254897219790831747

I don't think this message shows there can be vaults with underlyings with different decimals. This message only shows which tokens can be considered underlying, but has no info on several tokens being underlying in one Vault. This message was then mentioned in my public statement where the in-scope tokens were updated.

About other messages, there were no public statements from my side, hence, the judging rules apply, since they do not stand above them:

> Discord messages or DM screenshots are not considered sources of truth while judging an issue/escalation especially if they are conflicting with the contest README

The sources that can override the judging rules are README and the code comments. As far as I'm aware, there is no info in the README or code comments talking about having underlying tokens with different decimals. 

Hence, the judging rules apply and we have to assume the admin will use the values that will not cause any issues, i.e. tokens with the same decimals.

> Actually it doesn't matter whatever the base token is , if two underlying tokens with different decimals are used it will cause problems . In discord the sponsor used the example and it was denoting 2 underlying tokens only

Excuse me, I got confused by previous comments and thought the problem arises even when base token decimals != underlying token decimals.

If I understood your message correctly and reflected on it, then the decision remains the same, reject the escalation based on the fact that admin can use vaults with the same decimals, which won't cause any issues. 

If I'm incorrect, looking forward to your reply with correcting my statements.

**Comment by ADK0010** [comment]
"As far as I'm aware, there is no info in the README or code comments talking about having underlying tokens with different decimals." - You are correct on it as the information of even using Usdc & Usdt was added midway during the contest , so the only way we could interpret it was through Discord messages of Sponsor . 
It is true that for normal situations this rule applies - 
`Discord messages or DM screenshots are not considered sources of truth while judging an issue/escalation especially if they are conflicting with the contest README`
And I 100% agree with you, but this is not a normal situation as the Usdc & Usdt was added midway during contest .
Due to midway addition of Usdc & Usdt to contest , the readme doesn't reflect whether the sponsor wants to use tokens with different decimals together or not . The only source of truth available for watson's are Discord messages of Sponsor, & as I said earlier , in this message-
https://discord.com/channels/812037309376495636/1252276613417013353/1254898899852857446
the sponsor gives an example of depositing Usdc & Weth(different decimal underlying tokens) .

**Comment by WangSecurity** [comment]
I see your confusion, there are two rules:
1: 
> The Sherlock Judge can use public statements up until 24h before the contest ends to override the language in the chosen source of truth

2:
> Discord messages or DM screenshots are not considered sources of truth while judging an issue/escalation especially if they are conflicting with the contest README

For USDC and USDT being added to the scope, there was a public statement by me (Sherlock Judge), see [here](https://discord.com/channels/812037309376495636/1252276613417013353/1254895536629219428). Hence, the first rule applies. Additionally, this message has a `here` tag and was pinned

For vaults having 2+ underlying tokens with different decimals, there was no public by me. Hence, the second rule applies.

Hope that explains why the message about USDT and USDC being in-scope is considered here and why the second is not. The decision remains the same based on the same arguments as [here](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/160#issuecomment-2252848389). Planning to reject the escalation and leave the issue as it is.

**Comment by IWildSniperI** [comment]
those inconsistencies are really confusing to me as an auditor. never knew those were the use cases and i can refer to HoJ doing the same as me and @ADK0010 thought

see [here](https://github.com/sherlock-audit/2024-05-andromeda-ado-judging/issues/47#issuecomment-2228343549)

issue referred got escalation resolved around public discord statement even after contest ended. i know that historical decisions are not source for future ones but they just hurts

in addition to that, we know the intent of sponsor from his deployment script (i think this role is not documented right? although we just still use it for validation and invalidation) so that we can get some initial thoughts of what he wanted, then this is the same with discord public messages.

> if they are conflicting with the contest README

the message doesn't conflict with the readMe right?

**Comment by WangSecurity** [comment]
Yep, I see where the confusion comes from. In the issue you sent, the question to the sponsor was about the intended design. I believe these questions are viable both during the contest and after the contest to understand how the protocol works. But, what we're talking about here is the admin setting variables to specific values, in this case underlying tokens with different decimals, which would brick the protocol. Hence, based on the rules, this issue, specifically, should be invalid. While, as I understand, the issue you've quoted is a different scenario, where we talk about how the protocol should function.

Also, take note that it wasn't me who resolved escalations on Andromeda and I don't have enough context. Moreover, this contest and Andromeda used different rules about admins. Hence, from my perspective, the rules are clear here, but I see confusion from your side, so I would be glad to discuss it in detail outside of this discussion in Discord (either in the feedback channel or in DMs, whatever you prefer).

The decision remains the same, planning to reject the escalation and leave the issue as it is, based on the admin rules.

**Comment by IWildSniperI** [comment]
So i think we can ask the sponsor to confirm if its intended to have both isdc and wsteth in same vault, right?

**Comment by WangSecurity** [comment]
> So i think we can ask the sponsor to confirm if its intended to have both isdc and wsteth in same vault, right?

This scenario of adding usdc and wsteth in the same vault is considered invalid based on the the admin rules. Even if we ask the sponsor and they agree it can happen, this statement cannot stand above the judging rules. 

Hence, the decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by IWildSniperI** [comment]
> Watsons are expected to keep up to date with the contest's Discord channel as important announcements impacting judging may arise. They should keep in mind that any message the Sponsor sends will be considered a source of truth.

I see this rule would imply on the discord message mentioned by the fellow Watson above?, or what does this mean?

Especially this **They should keep in mind that any message the Sponsor sends will be considered a source of truth.**

**Comment by WangSecurity** [comment]
Thank you for asking, but it doesn't mean the Sponsor's messages are considered above the rules and override the README.

To re-iterate, if the public announcement by me was made in the contest channel on Discord, it can override any source of truth:

> The Sherlock Judge can use public statements up until 24h before the contest ends to override the language in the chosen source of truth.
important announcements impacting judging may arise

 If the message was sent by the Sponsor it's a source of truth to understand how the protocol should work and function, but it doesn't override other sources of truth or stand above judging rules.

Hence, the decision remains the same, planning to reject the escalation and leave the issue as it is.
> If no values are provided, the (external) admin is trusted to use values that will not cause any issues.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Al-Qa-qa](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/160/#issuecomment-2228774818): rejected
