### ISSUE TITLE
ArsenLupin - DepositWrapper could become non-usable

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-mellow-judging#201]
ArsenLupin

Medium

# DepositWrapper could become non-usable

## Summary
The devs declared that there would be more that 1 underlying tokens in the protocol. Additionally, the Vault.sol has a method to add underlying token, so it is clear that the underlying token.length could be more than 1.

```
As underlyingTokens only [weth, wsteth, reth, usdc, usdt] can be used
actually underlying tokens are only [wsteth, weth] + new ones
```

However, it creates the problem for the user who would like to deposit via the DepositWrapper. Let’s see how exactly. 

In the DepositWrapper in the deposit function there is a check which revert the function if the underlyingTokens.length > 1. It means that once the vault.underlyingTokens() length would become > 1, the deposit function would become non-usable.

```solidity
 address[] memory tokens = vault.underlyingTokens();
        if (tokens.length != 1 || tokens[0] != wsteth)
            revert InvalidTokenList();
```

## Vulnerability Detail
- Owner add one more underlying token (apart from the wsETH)
- User tries to deposit stETH via the DepositWrapper
- Since `tokens.length != 1`  but it is equal to 2 the function would revert.

## Impact
DepositWrapper contract becomes non usable once the underlying token length > 1

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/utils/DepositWrapper.sol#L52-L53

## Tool used
Manual Review

## Recommendation
```solidity
if (tokens[0] != wsteth)
 revert InvalidTokenList();
```

**Comment by ArsenSecurity** [comment]
Escalate
The vulnerability clearly shows that if the amount of the underlying tokens will be > 1, the Deposit Wrapper will become non-usable. For such scenario it isn't important which tokens exactly will be "underlying", but what important is that users will not be able to deposit funds apart from underlying tokens(that's why the depositWrapper exists), it serves the purpose of converting the tokens into the underlying ones. But since it will not be possible with the current implementation, i highly suggest to adjust the code or completely remove the DepositWrapper contract, since based on your response it seems that it is not "useful" any more

**Comment by sherlock-admin3** [comment]
> Escalate
> The vulnerability clearly shows that if the amount of the underlying tokens will be > 1, the Deposit Wrapper will become non-usable. For such scenario it isn't important which tokens exactly will be "underlying", but what important is that users will not be able to deposit funds apart from underlying tokens(that's why the depositWrapper exists), it serves the purpose of converting the tokens into the underlying ones. But since it will not be possible with the current implementation, i highly suggest to adjust the code or completely remove the DepositWrapper contract, since based on your response it seems that it is not "useful" any more

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
In the [script](https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/scripts/mainnet/Deploy.s.sol#L9) are there any vaults with >1 underlying tokens, are there any live pools with >1 underlying tokens? 

And as I understand, the function would work if there's only one underlying token and the user wants to deposit a different one (deposit token != underlying)?

**Comment by ArsenSecurity** [comment]
Escalate
Such behaviour breaks core contract functionality, rendering the contract (DepositWrapper) useless. There is clearly seen that the Vault.sol has addToken/removeToken functions, it means that the `_underlyingTokens` will be increased/decreased.
Based on that, we can clearly seen once this prerequisite will be done, the DepositWrapper will become useless for such kind of Vault -> https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/utils/DepositWrapper.sol#L52-L53

**Comment by 0xHuntoor** [comment]
would you kindly sir refer to [discussion around this message?](https://discord.com/channels/812037309376495636/1252276613417013353/1255561680406970379)
cause obviously this seems like an extension for `wstETH` only vaults
correct me if i am wrong

**Comment by ArsenSecurity** [comment]
Correct me if i miss something. The overall logic of the depositWrapper is "to make life easier for users. They come and want to deposit not only wsteth, but eth/weth/steth. We let them do it"
From the docs: DepositWrapper contract is a utility that wraps deposits of various tokens into a specific vault asset. It allows for deposits in ETH, WETH, stETH and wstETH.

So, it is clear that if more than 1 underlying token could is used in the Vault, assume Wsteth + another. Then, the DepositWrapper become useless. I clearly see that deposit can be made directly, but since the DepositWrapper is in scope and such check clearly shows that if the Vault has >1 token, the contract is useless, i believe it is valid (correct me if so)
`if (tokens.length != 1 || tokens[0] != wsteth)
            revert InvalidTokenList();`

 If there would be 2 underlying token -> wsEth and another. The user will have no opportunity to deposit easily the tokens that could be converted into the wsEth, the user will be forced to deposit directly wsEth token. It is incorrect, because the  depositWrapper is to make life easier for users, but in such scenario user will be forced to manually find the way to convert steth, weth, eth into wsteth, instead of simply send it into the Wrapper

**Comment by 0xHuntoor** [comment]
@Senya123 the check is clearly indicating that this contract extension is only for Vaults with 1 token specifically `wstETH`
`if (tokens.length != 1) revert InvalidTokenList();`
`if (tokens[0] != wsteth) revert InvalidTokenList();`

if any of the above conditions is true we revert

**Comment by ArsenSecurity** [comment]
I see. It is clear that many Vaults will have the wstETH as a primary token. However, it doesn't mean that it will be the only one, because we have the addToken function. There is no information in the docs/readMe that there will be the Vaults that will hold only wstETH as underlying. And based on the function addToken we could clearly see, that in any point in time the DepositWrapper could become useless.

I would immediately agree with your dispute if the Vault.sol clearly defines that there is only one (wsteth) underlying token, but since it is not, i have a right to assume that based on the addToken function, Vault.sol serves a purpose of having multiple tokens.

**Comment by WangSecurity** [comment]
I believe the Deposit Wrapper works as it is designed. It is designed to deposit only ETH, WETH, stETH and WstETH andit is designed to only do that conversion to wstETH-based vaults where it's the only underlying token. I believe the contract here works as expected and intended. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Senya123](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/201/#issuecomment-2228113008): rejected
