### ISSUE TITLE
scammed - ChainlinkOracle doesn’t validate min/max answer and will return incorrect price during flash crashes

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#215]
scammed

Medium

# ChainlinkOracle doesn’t validate min/max answer and will return incorrect price during flash crashes

## Summary

Not validating the price against min/max values of the Chainlink Aggregators will fail to revert the transaction during price crashes and will open arbitrage opportunities in the Mellow Vaults.

https://medium.com/cyfrin/chainlink-oracle-defi-attacks-93b6cb6541bf#00ac

## Vulnerability Detail

From the deployment scripts we can observe the following Chainlink addresses will be used in the upcoming mainnet deployment:

- `stETH/ETH` - https://etherscan.io/address/0x716BB759A5f6faCdfF91F0AfB613133d510e1573#readContract
- `rETH/ETH` - https://etherscan.io/address/0x9cB248E68fb81d0CFE7D6B3265Fe6Bf123A71FE0#readContract

Both of these contracts are Chainlink aggregators and have minAnswer and maxAnswer functions, that are used to indicate and validate the price returned from `latestRoundData` and revert the transaction if the range doesn’t hold. The problem is that Mellow does not utilize these functions and will end up using extremely wrong prices in case there is a short crash of the price as [[Venus on BSC when LUNA imploded](https://rekt.news/venus-blizz-rekt/)](https://rekt.news/venus-blizz-rekt/).

```solidity
function _validateAndGetPrice(
    AggregatorData memory data
) private view returns (uint256 answer, uint8 decimals) {
    if (data.aggregatorV3 == address(0)) revert AddressZero();
    (, int256 signedAnswer, , uint256 lastTimestamp, ) = IAggregatorV3(
        data.aggregatorV3
    ).latestRoundData();
    // The roundId and latestRound are not used in the validation process to ensure compatibility
    // with various custom aggregator implementations that may handle these parameters differently
    if (signedAnswer < 0) revert InvalidOracleData();
    answer = uint256(signedAnswer);
    if (block.timestamp - data.maxAge > lastTimestamp) revert StaleOracle();
    decimals = IAggregatorV3(data.aggregatorV3).decimals();
}
```

That will lead to unfair lpToken pricing and users will end up extracting value from the protocol

## Impact

- wrong pricing of the lpToken, since it relies on all the underlying tokens to be converted to their ETH rate through `ChainlinkOracle` and when crash happens it will go unnoticed.

## Code Snippet

https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/oracles/ChainlinkOracle.sol#L56-L69

## Tool used

Manual Review

## Recommendation

Add min and max answer checks to `ChainlinkOracle`, as well as in the custom Aggregators add uint256 max and 1 answers.

Duplicate of #300

**Comment by 0x3b33** [comment]
Escalate

This issue is different from #300 and should be separated. Here we are explaining that due to missing `min/max` answer checks (that are included in both `rETH` and `stETH` aggregators) system will continue to deliver prices even when one of the aggregators starts showing a wrong price, exactly what happened on Luna crash. 

The fact that releases are still targeting exactly this feature of the aggregators makes it clear that these checks are still supported and the integrators should use them, otherwise they risk mispricing the assets. - https://github.com/smartcontractkit/chainlink-local/pull/12#pullrequestreview-2152666670

https://docs.sherlock.xyz/audits/judging/judging#viii.-list-of-issue-categories-that-are-considered-valid

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue is different from #300 and should be separated. Here we are explaining that due to missing `min/max` answer checks (that are included in both `rETH` and `stETH` aggregators) system will continue to deliver prices even when one of the aggregators starts showing a wrong price, exactly what happened on Luna crash. 
> 
> The fact that releases are still targeting exactly this feature of the aggregators makes it clear that these checks are still supported and the integrators should use them, otherwise they risk mispricing the assets. - https://github.com/smartcontractkit/chainlink-local/pull/12#pullrequestreview-2152666670
> 
> https://docs.sherlock.xyz/audits/judging/judging#viii.-list-of-issue-categories-that-are-considered-valid

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by z3s** [comment]
> Chainlink Price Checks: Issues related to minAnswer and maxAnswer checks on Chainlink's Price Feeds are considered medium only if the Watson explicitly mentions the price feeds (e.g. USDC/ETH) that require this check.

If `stETH/ETH` and `rETH/ETH` require this check, this could be a valid Medium issue.

**Comment by blckhv** [comment]
https://etherscan.io/address/0x716BB759A5f6faCdfF91F0AfB613133d510e1573#readContract
![Screenshot 2024-07-16 at 5 02 52 PM](https://github.com/user-attachments/assets/777a58cb-e92c-4ec1-a653-c768ac62fd9e)

**Comment by IronsideSec** [comment]
https://github.com/sherlock-audit/2024-06-mellow-judging/issues/158 also talks about same `min and max answer` but got duped into `price validation` like this issue. Consider #158 too.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept it and validate the report with medium severity, based on this rule:
> Chainlink Price Checks: Issues related to minAnswer and maxAnswer checks on Chainlink's Price Feeds are considered medium only if the Watson explicitly mentions the price feeds (e.g. USDC/ETH) that require this check

#158 is not a sufficient duplicate based on the rule above. @z3s are there any duplicates?

Additionally, the rETH price feed doesn't have the `minAnswer`/`maxAnswer` actually, check [this](https://stackoverflow.com/questions/78558661/which-chainlinks-price-feeds-still-have-minanswer-and-maxanswer-checks).

**Comment by z3s** [comment]
The reason I duplicated this min/max check and zero check was the main submission #300 mentioned both scenarios.
> are there any duplicates?

#300 #58 #101 mentioned the problem, but didn't say it is `required`.

`stETH/ETH` min/max returns 0.001/100 eth, the mentioned impact is "using extremely wrong prices in case there is a short crash of the price", I mean are these min/max numbers even that helpful in such situations?

**Comment by blckhv** [comment]
> Additionally, the rETH price feed doesn't have the minAnswer/maxAnswer actually, check [this](https://stackoverflow.com/questions/78558661/which-chainlinks-price-feeds-still-have-minanswer-and-maxanswer-checks).

Actually it has them here - https://etherscan.io/address/0x9cB248E68fb81d0CFE7D6B3265Fe6Bf123A71FE0#readContract, but as mentioned in the Chainlink's documentation these numbers mean they're disabled, but in other aggregators they're configured - USDC/ETH, for example which will also be used.

Two issues should be separated, the main criteria for [duplicated issues](https://docs.sherlock.xyz/audits/judging/judging#ix.-duplication-rules) is to have the same root cause. In this situation, the root cause of this issue is the min/max boundaries not being checked, whereas the other one is simply for handling the scenario when the price feed returns 0.

**Comment by 10xhash** [comment]
> Agree with the escalation, planning to accept it and validate the report with medium severity, based on this rule:
> 
> > Chainlink Price Checks: Issues related to minAnswer and maxAnswer checks on Chainlink's Price Feeds are considered medium only if the Watson explicitly mentions the price feeds (e.g. USDC/ETH) that require this check
> 
> #158 is not a sufficient duplicate based on the rule above. @z3s are there any duplicates?
> 
> Additionally, the rETH price feed doesn't have the `minAnswer`/`maxAnswer` actually, check [this](https://stackoverflow.com/questions/78558661/which-chainlinks-price-feeds-still-have-minanswer-and-maxanswer-checks).

stETH/ETH is not used in the current deployment. The rate of stETH is explicitly assumed to be 1:1 with weth and mentioned publicly by the sponsor. And the reth/eth doesn't suffer from the min/max answer limits because they have disabled it by keeping it to (1,type(int176).max)

**Comment by blckhv** [comment]
Can you, abstracting from the sponsor's words, state that stETH/WETH **always** has a 1:1 ratio? 
> stETH/ETH is not used in the current deployment. 

wsETH/ETH is being used, you're right, but in order to derive the price of the wsETH we need stETH/ETH feed, as there is no direct price feed for wsETH/ETH.
Also, as I mentioned USDC/ETH aggregator will also be needed since the sponsor added it as a supported asset and it requires min/max answer checks as well.

**Comment by WangSecurity** [comment]
To confirm, the Chainlink oracle is used only for underlying tokens or for both underlying and whitelisted tokens?

**Comment by blckhv** [comment]
small correction - underlying tokens are indeed whitelisted tokens. The oracle will be needed for all the underlying tokens.

**Comment by WangSecurity** [comment]
But, as I understand from spnsor's message in discord underlying != whitelisted https://discord.com/channels/812037309376495636/1252276613417013353/1254897291622617240 ? @blckhv

**Comment by blckhv** [comment]
eth is the base, stETH is supported as an deposit asset which is always converted to wstETH and wsETH, rETH, USDC, USDT are assets that will be supported as Vault assets, if that answers your question

**Comment by WangSecurity** [comment]
As I understand, underlying tokens can only be the following:
weth, wsteth, reth, usdc, usdt

Whitelisted are the ones that can be used in `DepositWrapper` and converted into `wstEth`, so the users don't have to convert them externally. It doesn't require to use of the `stETH` price feed and it will done directly via WETH, WstETH and stETH contracts.

So the min and max answer check on stETH won't affect the price of LPToken since stETH won't be used as an underlying token or base token (as seen in the deployment script [here](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/scripts/mainnet/DeployScript.sol#L126-L128)). I know that USDC has one and USDC will be used as an underlying token. However, the USDC min and max answer case is not mentioned in the report. Hence, I'll have to keep this report invalid, since it doesn't link the price feed that has min and max answers that would indeed affect the protocol. Planning to reject the escalation.

**Comment by blckhv** [comment]
So #266 also states that stETH/ETH price feed will indeed be used as part of pricing the wstETH token:
> The cross-oracle price check is required for WSTETH/STETH and then STETH/ETH price check but should not be enforced for every underlying token used in the protocol.

Per my understanding the usage of this feed is a **must** for correctly pricing the wstETH. 
For reference you can look how Lido implements wstETH/ETH feed - https://github.com/lidofinance/wsteth-eth-price-feed/blob/main/contracts/AAVECompatWstETHToETHPriceFeed.sol#L39-L45

**Comment by WangSecurity** [comment]
Yep, after looking into the discussion under #266, I see that the standard Chainlink oracles are not even used here and Mellow has custom ones, so as I understand, the `minAnswer` and `maxAnswer` issues are not relevant here and will not cause any problems. But, I see in the report you say these oracles are used in the Deployment script, but I couldn't find them in the deployment scripts linked in the README. The only address for aggregators I see are WstETH aggregator and WETH aggregator [here](https://github.com/mellow-finance/mellow-lrt/blob/628b862bf62ff05612099d382a9dcfcb6c1fc4a2/scripts/mainnet/Deploy.s.sol#L68C2-L72C72) and these are basically `WStethRatiosAggregatorV3` and `ConstantAggregatorV3`, respectively. If I'm incorrect and the aggregators you linked are in the deployment script, please refer me to it.

Until then, the decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #300

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/215/#issuecomment-2230412921): rejected
