### ISSUE TITLE
scammed - Deposit placed between remove and add module will receive more lpTokens

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-mellow-judging#219]
scammed

Medium

# Deposit placed between remove and add module will receive more lpTokens

## Summary

Due to a design decision to not include a token balance check in the `removeTvlModule` function, it is possible for a module with a non-zero token balance to be removed:

```solidity
function removeTvlModule(address module) external nonReentrant {
      _requireAdmin();
      if (!_tvlModules.contains(module)) revert InvalidState();
      _tvlModules.remove(module);
      emit TvlModuleRemoved(module);
  }
```

## Vulnerability Detail

There is no check for the balance of a token in module, similar to `removeToken` and there is no way module to be replaced than simply calling remove and then add as explained in the docs:

> It is important to note that there is no such check when calling `removeTvlModule`, so when updating parameters, sequential execution of a transaction to remove the old and add the new tvlModule is implied.
> 

The problem is when depositors place their transactions between `removeTvlModule` and `addTvlModule` as they will receive increased amount of lpTokens simply because the overall token balance decreases when `TvlModule` that has non-zero balance is being removed:

```solidity
/// @inheritdoc IVault
function deposit(
    address to,
    uint256[] memory amounts,
    uint256 minLpAmount,
    uint256 deadline
)
    external
    nonReentrant
    checkDeadline(deadline)
    returns (uint256[] memory actualAmounts, uint256 lpAmount)
{
    (
        address[] memory tokens,
        uint256[] memory totalAmounts
    ) = underlyingTvl();

    uint256 depositValue = 0;
    uint256 totalValue = 0;
    actualAmounts = new uint256[](tokens.length);
    IPriceOracle priceOracle = IPriceOracle(configurator.priceOracle());
    for (uint256 i = 0; i < tokens.length; i++) {
        uint256 priceX96 = priceOracle.priceX96(address(this), tokens[i]);
        totalValue += totalAmounts[i] == 0
            ? 0
            : FullMath.mulDivRoundingUp(totalAmounts[i], priceX96, Q96);
        if (ratiosX96[i] == 0) continue;
        uint256 amount = FullMath.mulDiv(ratioX96, ratiosX96[i], Q96);
        IERC20(tokens[i]).safeTransferFrom(
            msg.sender,
            address(this),
            amount
        );
        actualAmounts[i] = amount;
        depositValue += FullMath.mulDiv(amount, priceX96, Q96);
    }

    lpAmount = _processLpAmount(to, depositValue, totalValue, minLpAmount);
    emit Deposit(to, actualAmounts, lpAmount);
    address callback = configurator.depositCallback();
    if (callback == address(0)) return (actualAmounts, lpAmount);
    IDepositCallback(callback).depositCallback(actualAmounts, lpAmount);
    emit DepositCallback(callback, actualAmounts, lpAmount);
}

 function _processLpAmount(
        address to,
        uint256 depositValue,
        uint256 totalValue,
        uint256 minLpAmount
    ) private returns (uint256 lpAmount) {
        uint256 totalSupply = totalSupply();
			 else {
            lpAmount = FullMath.mulDiv(depositValue, totalSupply, totalValue);
            if (lpAmount < minLpAmount) revert InsufficientLpAmount();
            if (to == address(0)) revert AddressZero();
        }
    }
```

Between the two transactions the following variables, used in `vault::deposit` will be **decreased**:

- `totalAmounts` - since `vault::underlyingTvl` iterates over the active modules and sum up the assets
- `totalValue` - since it relies on the `totalAmounts` * assetPrice

The other variables forming the price of the lpToken are `amounts` and `depositValue`, that are controlled by the attacker. 

```solidity
lpAmount = FullMath.mulDiv(depositValue, totalSupply, totalValue);
// (depositValue (⬆️) * totalSupply) / totalValue (⬇️)
```

## Impact

Due to the missing check - instant discount for the lpAssets when Module containing non-zero balance is being removed, decreasing the overall Tvl in the system.

## Code Snippet

https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/Vault.sol#L285-L368

## Tool used

Manual Review

## Recommendation

Add check whether there are tokens in the Bonds for which the `DefaultBondTvlModule` is accounting for.

**Comment by 0x3b33** [comment]
Escalate

This report showcases how user can place his transaction between module update and receive more lp tokens due to the increased exchange rate.

It will be all possible due to the design
decision of the protocol team to not have atomic module update mechanism which is the root cause of the issue.
https://mellowprotocol.notion.site/Vault-d8c1a4aa20fe476ea7dc5bfa5ea78d07#ca6716b182b04251a7ffd18619d57663

Due to the modular architecture of the Mellow system and the fact that many Vaults with many module configurations will be deployed, updates will be often needed and they will be always used to sandwich malicious deposit transaction resulting in more tokens minted since as we described the denominator (totalValue) decreases as it is fetched from the module

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This report showcases how user can place his transaction between module update and receive more lp tokens due to the increased exchange rate.
> 
> It will be all possible due to the design
> decision of the protocol team to not have atomic module update mechanism which is the root cause of the issue.
> https://mellowprotocol.notion.site/Vault-d8c1a4aa20fe476ea7dc5bfa5ea78d07#ca6716b182b04251a7ffd18619d57663
> 
> Due to the modular architecture of the Mellow system and the fact that many Vaults with many module configurations will be deployed, updates will be often needed and they will be always used to sandwich malicious deposit transaction resulting in more tokens minted since as we described the denominator (totalValue) decreases as it is fetched from the module

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Is it documented that the protocol will indeed remove the modules with tokens inside them, or maybe there's contextual evidence of it?

**Comment by 0xHuntoor** [comment]
> Due to a design decision to not include a token balance check in the removeTvlModule function, it is possible for a module with a non-zero token balance to be removed:

The question is: why would an Admin do such a harmful Act that will lead to sudden decrease in TVL

This issue is like checking address(0) when adding new token, this is an admin function

Secondly and most importantly 
even if so, he can add TVL module first then remove the old

I see this in sherlock Docs
> Admin functions are assumed to be used properly, unless a list of requirements is listed and it's incomplete or if there is no scenario where a permissioned funtion can be used properly.

**Comment by blckhv** [comment]
From Mellow's documentation:
> Vault also has the functionality of adding and removing underlyingTokens, as well as tvlModules. For this purpose, the following functions are available, which can only be called by the vault's admin: addToken, removeToken, addTvlModule, removeTvlModule. Upon calling removeToken, it is checked that the underlyingTvl function for the specified token returns a zero value. Otherwise, the function reverts with a NonZeroValue error. It is important to note that there is no such check when calling removeTvlModule, so when updating parameters, sequential execution of a transaction to remove the old and add the new tvlModule is implied.

>  Upon calling removeToken, it is checked that the underlyingTvl function for the specified token returns a zero value. Otherwise, the function reverts with a NonZeroValue error.

We can see for this function it is mentioned that token with non-zero balance **can't** be removed.

> It is important to note that there is no such check when calling removeTvlModule, so when updating parameters, sequential execution of a transaction to remove the old and add the new tvlModule is implied.

Unlike here we can see the mentioned order is remove -> add, without mentioning that the module should not contain tokens, the protocol team would have placed the same check if they wanted only modules with zero token balance to be removed.

**Comment by 0xHuntoor** [comment]
Docs are never a source of truth

**Comment by WangSecurity** [comment]
The comment above is not completely correct, the documentation is a source of truth, but doesn't override the rules. Hence, I believe since it's not documented in the README or code comments, what the admin will do, the judging rules should apply. In this case, we have to believe the admins will use the functions correctly so it doesn't cause any loss of value of LP tokens allowing to get them at a lower price. And will not remove modules with funds in them.

Planning to reject the escalation and leave the issue as it is.

**Comment by blckhv** [comment]
> I believe since it's not documented in the README or code comments, what the admin will do, **the judging rules should apply**. In this case, we have to believe the admins will use the functions correctly so it doesn't cause any loss of value of LP tokens allowing to get them at a lower price. And will not remove modules with funds in them.

Correct me if I'm wrong but this text from the Mellow documentation clearly mentions the order of the operations:
> It is important to note that there is no such check when calling removeTvlModule, so when updating parameters, sequential execution of a transaction to remove the old and add the new tvlModule is implied.

> And will not remove modules with funds in them.

How we can assume that, since the initial step towards wrong module removal is there? 
I disagree there is no way admins to force the Vault to not have any funds inside. Even because as we observed in #116, withdrawal fees can stay in the Vault. Also we can't conclude admins will not be **forced** to remove module with funds in it. While I understand the borderline of this issue regarding admin actions, the impact from performing such action is high as everyone will be able to extract big amount of value from the protocol by simply placing his deposit after such removal.

From Sherlock's documentation:
> Note: Despite these rules, we must understand that because of the complexity & subjective nature of smart contract security, there may be issues that are judged beyond the purview of this guide. However, for the vast majority of cases, this guide should suffice. Sherlock's internal judges continue to have the last word on considering any issue as valid or not.

Saying that you haven't expressed your thought about the impact of the issue, but we only elaborate on the admin actions.  As we can't assume how the admin will behave, we must rely on the code and NATSPEC. 
I must have mentioned earlier that the exact same comment, regarding the order of module replacement can be found in the [IVault](https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/interfaces/IVault.sol#L57-L58):

https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/interfaces/IVault.sol#L57-L58
> Upon calling removeToken, it is checked that the underlyingTvl function for the specified token returns a zero value. Otherwise, the function reverts with a NonZeroValue error. 
It is important to note that there is no such check when calling removeTvlModule, so when updating parameters, sequential execution of a transaction to remove the old and add the new tvlModule is implied.

**Comment by WangSecurity** [comment]
> Correct me if I'm wrong but this text from the Mellow documentation clearly mentions the order of the operations

It does, but the documentation doesn't stand above the rules and it doesn't give the list of requirements and only says the protocol intentionally removed the check for value.

> How we can assume that, since the initial step towards wrong module removal is there?
I disagree there is no way admins to force the Vault to not have any funds inside. Even because as we observed in https://github.com/sherlock-audit/2024-06-mellow-judging/issues/116, withdrawal fees can stay in the Vault. Also we can't conclude admins will not be forced to remove module with funds in it. While I understand the borderline of this issue regarding admin actions, the impact from performing such action is high as everyone will be able to extract big amount of value from the protocol by simply placing his deposit after such removal

The impact depends on the TVL of the removed module, and the smaller the TVL, the smaller will be the decrease in lpToken price. Additionally, admins can remove the withdrawal fees from the module as we said in the discussion below #116.

> From Sherlock's documentation:
Note: Despite these rules, we must understand that because of the complexity & subjective nature of smart contract security, there may be issues that are judged beyond the purview of this guide. However, for the vast majority of cases, this guide should suffice. Sherlock's internal judges continue to have the last word on considering any issue as valid or not.
Saying that you haven't expressed your thought about the impact of the issue, but we only elaborate on the admin actions. As we can't assume how the admin will behave, we must rely on the code and NATSPEC

I see that I have the ability to make judgements beyond the rules, but I don't think it's the case here. I understand the impact, but the impact can be even 0 if done correctly. We can and should assume the admins will behave correctly and will use functions in a way to not cause any issues. Even relying on the NATSPEC, we can assume the admins will call these 2 functions in 1 transaction, which will also eliminate this issue.

Hence, the decision remains the same. I still believe the admin rule applies here and this issue should remain invalid. Planning to reject the escalation.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/219/#issuecomment-2230405219): rejected
