### ISSUE TITLE
sandy - ``ISteth(steth).submit`` function doesn't return the exact amount of stETH as input ETH amount which can cause reverting of consequent functions.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-mellow-judging#252]
sandy

High

# ``ISteth(steth).submit`` function doesn't return the exact amount of stETH as input ETH amount which can cause reverting of consequent functions.

## Summary
``ISteth(steth).submit`` function doesn't return the exact amount of stETH as input ETH amount which can cause reverting of consequent functions.

## Vulnerability Detail
In the ``DepositWrapper`` contract, we can deposit ``ETH`` and it is then converted to ``stETH`` and then to ``wstETH``. 
First ETH is converted to ``stETH``:
```solidity
    function deposit(
        address to,
        address token,
        uint256 amount,
        uint256 minLpAmount,
        uint256 deadline
    ) external payable returns (uint256 lpAmount) {
        address wrapper = address(this);
        address sender = msg.sender;
        address[] memory tokens = vault.underlyingTokens();
        if (tokens.length != 1 || tokens[0] != wsteth)
            revert InvalidTokenList();
        if (amount == 0) revert InvalidAmount();
        if (token == steth) {
            IERC20(steth).safeTransferFrom(sender, wrapper, amount);
            amount = _stethToWsteth(amount);
        } else if (token == weth) {
            IERC20(weth).safeTransferFrom(sender, wrapper, amount);
            amount = _wethToWsteth(amount);
        } else if (token == address(0)) {
            if (msg.value != amount) revert InvalidAmount();
            amount = _ethToWsteth(amount);
...
```
```solidity
    function _ethToWsteth(uint256 amount) private returns (uint256) {
        ISteth(steth).submit{value: amount}(address(0));
        return _stethToWsteth(amount);
    }
```
It uses ``ISteth(steth).submit{value: amount}(address(0))`` to convert ``ETH`` to ``stETH`` and same amount is used to convert from ``stETH`` to ``wstETH``. The problem is if submit doesn't return same ``amount`` of ``ETH`` deposited, the conversion of ``stETH`` to ``wstETH``will revert due to insufficient funds and ``DepositWrapper`` contract doesn't hold any funds.
```solidity
    function _stethToWsteth(uint256 amount) private returns (uint256) {
        IERC20(steth).safeIncreaseAllowance(wsteth, amount);
        IWSteth(wsteth).wrap(amount);
        return IERC20(wsteth).balanceOf(address(this));
    }
```
> This same issue also exists in ``StakingModule`` contract too and any contract/function using ``convertAndDeposit()`` of ``StakingModule`` contract can also revert.
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/modules/obol/StakingModule.sol#L79

## Impact
Contract Functionality DoS.

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/utils/DepositWrapper.sol#L31
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/modules/obol/StakingModule.sol#L79

## Tool used
Manual Review

## Recommendation
Modify the ``_ethToWsteth`` of ``DepositWrapper`` as below:
```solidity
    function _ethToWsteth(uint256 amount) private returns (uint256) {
        uint256 balanceBefore = IERC20(steth).balanceOf(address(this));
        ISteth(steth).submit{value: amount}(address(0));
        return _stethToWsteth(IERC20(steth).balanceOf(address(this)) - balanceBefore);
    }
```

Duplicate of #299

**Comment by 0xSandyy** [comment]
Escalate

This is not a duplicate of https://github.com/sherlock-audit/2024-06-mellow-judging/issues/299. 299 is a 1-2 wei corner case when ``transferFrom()`` is used. That is not the case here.

The issue here is ``submit()`` function doesn't return the exact ``steth`` amount here but instead it returns ``shares`` instead of the actual token amount and they are not equal amounts.

Here is the implementation of the lido.fi ``submit()``:
https://github.com/lidofinance/lido-dao/blob/5fcedc6e9a9f3ec154e69cff47c2b9e25503a78a/contracts/0.4.24/Lido.sol#L922-L947

```solidity
    function _submit(address _referral) internal returns (uint256) {
        require(msg.value != 0, "ZERO_DEPOSIT");


        StakeLimitState.Data memory stakeLimitData = STAKING_STATE_POSITION.getStorageStakeLimitStruct();
        // There is an invariant that protocol pause also implies staking pause.
        // Thus, no need to check protocol pause explicitly.
        require(!stakeLimitData.isStakingPaused(), "STAKING_PAUSED");


        if (stakeLimitData.isStakingLimitSet()) {
            uint256 currentStakeLimit = stakeLimitData.calculateCurrentStakeLimit();


            require(msg.value <= currentStakeLimit, "STAKE_LIMIT");


            STAKING_STATE_POSITION.setStorageStakeLimitStruct(stakeLimitData.updatePrevStakeLimit(currentStakeLimit - msg.value));
        }


        uint256 sharesAmount = getSharesByPooledEth(msg.value);


        _mintShares(msg.sender, sharesAmount);


        _setBufferedEther(_getBufferedEther().add(msg.value));
        emit Submitted(msg.sender, msg.value, _referral);


        _emitTransferAfterMintingShares(msg.sender, sharesAmount);
        return sharesAmount;
    }
```
We can see, amount returned is ``sharesAmount`` and it is calculated as:
https://github.com/lidofinance/lido-dao/blob/5fcedc6e9a9f3ec154e69cff47c2b9e25503a78a/contracts/0.4.24/StETH.sol#L300C1-L304C6

```solidity
    function getSharesByPooledEth(uint256 _ethAmount) public view returns (uint256) {
        return _ethAmount
            .mul(_getTotalShares())
            .div(_getTotalPooledEther());
    }
```
and as per the ``lido.fi`` documentation:
https://docs.lido.fi/guides/lido-tokens-integration-guide#steth-internals-share-mechanics
> The share is a basic unit representing the stETH holder's share in the total amount of ether controlled by the protocol.

> Also, the impact I mentioned reverting is one impact whereas if shares amount is calculated less than the deposited amount, the users loses assets. Thus the severity of this issue should be high, same as the referenced issue below.

Similar issue in a contest last month: https://github.com/sherlock-audit/2024-05-sophon-judging/issues/4.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is not a duplicate of https://github.com/sherlock-audit/2024-06-mellow-judging/issues/299. 299 is a 1-2 wei corner case when ``transferFrom()`` is used. That is not the case here.
> 
> The issue here is ``submit()`` function doesn't return the exact ``steth`` amount here but instead it returns ``shares`` instead of the actual token amount and they are not equal amounts.
> 
> Here is the implementation of the lido.fi ``submit()``:
> https://github.com/lidofinance/lido-dao/blob/5fcedc6e9a9f3ec154e69cff47c2b9e25503a78a/contracts/0.4.24/Lido.sol#L922-L947
> 
> ```solidity
>     function _submit(address _referral) internal returns (uint256) {
>         require(msg.value != 0, "ZERO_DEPOSIT");
> 
> 
>         StakeLimitState.Data memory stakeLimitData = STAKING_STATE_POSITION.getStorageStakeLimitStruct();
>         // There is an invariant that protocol pause also implies staking pause.
>         // Thus, no need to check protocol pause explicitly.
>         require(!stakeLimitData.isStakingPaused(), "STAKING_PAUSED");
> 
> 
>         if (stakeLimitData.isStakingLimitSet()) {
>             uint256 currentStakeLimit = stakeLimitData.calculateCurrentStakeLimit();
> 
> 
>             require(msg.value <= currentStakeLimit, "STAKE_LIMIT");
> 
> 
>             STAKING_STATE_POSITION.setStorageStakeLimitStruct(stakeLimitData.updatePrevStakeLimit(currentStakeLimit - msg.value));
>         }
> 
> 
>         uint256 sharesAmount = getSharesByPooledEth(msg.value);
> 
> 
>         _mintShares(msg.sender, sharesAmount);
> 
> 
>         _setBufferedEther(_getBufferedEther().add(msg.value));
>         emit Submitted(msg.sender, msg.value, _referral);
> 
> 
>         _emitTransferAfterMintingShares(msg.sender, sharesAmount);
>         return sharesAmount;
>     }
> ```
> We can see, amount returned is ``sharesAmount`` and it is calculated as:
> https://github.com/lidofinance/lido-dao/blob/5fcedc6e9a9f3ec154e69cff47c2b9e25503a78a/contracts/0.4.24/StETH.sol#L300C1-L304C6
> 
> ```solidity
>     function getSharesByPooledEth(uint256 _ethAmount) public view returns (uint256) {
>         return _ethAmount
>             .mul(_getTotalShares())
>             .div(_getTotalPooledEther());
>     }
> ```
> and as per the ``lido.fi`` documentation:
> https://docs.lido.fi/guides/lido-tokens-integration-guide#steth-internals-share-mechanics
> > The share is a basic unit representing the stETH holder's share in the total amount of ether controlled by the protocol.
> 
> > Also, the impact I mentioned reverting is one impact whereas if shares amount is calculated less than the deposited amount, the users loses assets. Thus the severity of this issue should be high, same as the referenced issue below.
> 
> Similar issue in a contest last month: https://github.com/sherlock-audit/2024-05-sophon-judging/issues/4. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
> The issue here is submit() function doesn't return the exact steth amount here but instead it returns shares instead of the actual token amount and they are not equal amounts

Could you please elaborate on the above, because as I see the `submit` function indeed returns `shares` but the amount of tokens minted == amount of returned shares

```
function _submit(address _referral) internal returns (uint256) {
        require(msg.value != 0, "ZERO_DEPOSIT");

        StakeLimitState.Data memory stakeLimitData = STAKING_STATE_POSITION.getStorageStakeLimitStruct();
        // There is an invariant that protocol pause also implies staking pause.
        // Thus, no need to check protocol pause explicitly.
        require(!stakeLimitData.isStakingPaused(), "STAKING_PAUSED");

        if (stakeLimitData.isStakingLimitSet()) {
            uint256 currentStakeLimit = stakeLimitData.calculateCurrentStakeLimit();

            require(msg.value <= currentStakeLimit, "STAKE_LIMIT");

            STAKING_STATE_POSITION.setStorageStakeLimitStruct(stakeLimitData.updatePrevStakeLimit(currentStakeLimit - msg.value));
        }

        uint256 sharesAmount = getSharesByPooledEth(msg.value);

        _mintShares(msg.sender, sharesAmount);

        _setBufferedEther(_getBufferedEther().add(msg.value));
        emit Submitted(msg.sender, msg.value, _referral);

        _emitTransferAfterMintingShares(msg.sender, sharesAmount);
        return sharesAmount;
    }
```

Lido stETH token address -- https://etherscan.io/address/0x17144556fd3424edc8fc8a4c940b2d04936d17eb#code

**Comment by 0xHuntoor** [comment]
1. my issue talks about similar condition #280 

2.  [reference of the issue in Lido Docs here](https://docs.lido.fi/guides/lido-tokens-integration-guide/#:~:text=stETH%20is%20a,1%20ratio%20though) 

- Lido in fact some times doesn't have 1 to 1 ETH to stETH

- the report is talking about returned shares which i see is wrong cause shares != tokens minted and shares doesn't mean tokens returned


tokens minted should be 1 to 1 what ever shares are 
- for example: i mint 1 stETH with 1 ETH that gives me 9e17 shares **(due to validator rewards shares are always less than tokens minted)**
- 9e17 are my shares and returned as **returned value** but my balance increases by 1e18 stETH balance


See this calculation for more understanding of shares
`shares[account] = balanceOf(account) * totalShares / totalPooledEther`

- in fact, in the future when validator rewards gets very big -> shares corresponding to stETH gets smaller but still should be 1 ETH = 1 stETH increase in balance

- will try to explain more if you want, but my issue mentioned above have different edge case

**Comment by 0xSandyy** [comment]
@WangSecurity It seems I made a mistake understanding my own issue while escalating. I got the idea for the issue from the comment here in the previous contest:
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L808-L813

One of the reports mentioned the same instance https://github.com/sherlock-audit/2024-05-sophon-judging/issues/4 and I assumed the same for this escalation and made a mistake explaining the issue. Apologies for that! 

But still, my original report is still valid and this issue is not a duplicate of https://github.com/sherlock-audit/2024-06-mellow-judging/issues/299.

```solidity
    function _ethToWsteth(uint256 amount) private returns (uint256) {
        ISteth(steth).submit{value: amount}(address(0));
        return _stethToWsteth(amount);
    }
```
Here, the same same ``amount`` used in ``ISteth(steth).submit{value: amount}(address(0));`` is used in ``_stethToWsteth(amount);``. Thus the code makes the assumption that amount of ``steth`` returned is equal to ``amount / msg.value`` sent. But this is wrong.  

Here are the event logs of recent ``submit()`` function calls in etherscan:

https://etherscan.io/tx/0x1d2b42bd426d7e72480a0bf3ae9092221ace3da388ab6bb9f0681d7fce8c0e37#eventlog
https://etherscan.io/tx/0x92e49035d297468b6a4abd881462681b8cd4941e20a43ca7faf1dc6d60b6b10e#eventlog

You can clearly see in the event logs that the amount of ``steth`` returned is ``1 wei`` less than the original ``msg.value`` sent.

Now coming back to the original code:
```solidity
    function _ethToWsteth(uint256 amount) private returns (uint256) {
        ISteth(steth).submit{value: amount}(address(0));
        return _stethToWsteth(amount);
    }
```
If the amount of ``steth`` returned is ``1 wei`` less than the ``amount``, the ``_stethToWsteth(amount)`` function will revert always due to insufficient funds.

The likelihood of this issue is high as it is seen in every ``submit()`` call. You can check yourself here: https://etherscan.io/txs?a=0xae7ab96520de3a18e5e111b5eaab095312d7fe84

**Comment by WangSecurity** [comment]
Thank you for clarification, indeed the mistake was in the escalation, not in the report. I believe this report and #299 are duplicates. Both have the same root cause, the `submit` and `transfer` functions of stETH convert the input amount into shares which can be 1-2 wei lower due to precision loss, resulting in the actual amount received 1-2 wei less than the input amount. Hence, the subsequent calls with the same `amount` will revert. I see that the issue happens in the different places of the code and requires fixing them separately, but the issue itself is the same.

The decision remains the same, keep them as duplicates and reject the escalation.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #299

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xSandyy](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/252/#issuecomment-2231715741): rejected
