### ISSUE TITLE
dany.armstrong90 - Users who try to emergency withdraw funds may have slippage loss.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#26]
dany.armstrong90

High

# Users who try to emergency withdraw funds may have slippage loss.

## Summary
Users who try to emergency withdraw funds may have slippage loss.

## Vulnerability Detail
`Vault.sol#emergencyWithdraw` function is the following.
```solidity
    function emergencyWithdraw(
        uint256[] memory minAmounts,
        uint256 deadline
    )
        external
        nonReentrant
        checkDeadline(deadline)
        returns (uint256[] memory actualAmounts)
    {
        uint256 timestamp = block.timestamp;
        address sender = msg.sender;
        if (!_pendingWithdrawers.contains(sender)) revert InvalidState();
        WithdrawalRequest memory request = _withdrawalRequest[sender];
384:    if (timestamp > request.deadline) {
            _cancelWithdrawalRequest(sender);
            return actualAmounts;
        }

        if (
390:        request.timestamp + configurator.emergencyWithdrawalDelay() >
            timestamp
        ) revert InvalidState();

        ......
    }
```
As can be seen from `L384` and `L390`, if `request.deadline` is before than `request.timestamp + configurator.emergencyWithdrawalDelay()`, emergency withdraw is impossible.
So, users who want to emergency withdraw funds have to set request deadline to be later than emergency withdraw delay.

However, the emergency withdraw delay may be long. 
For instance, it is 90 days in the `DeployScript.sol`.
This may cause users who try to emergency withdraw have slippage loss.

Scenario:
1. Assume that for a certain reason, administrator and operators don't process withdraw requests for a long time.
2. So a user sets request deadline to be later (ex: > 90 days) than emergency withdraw delay and registers withdraw request in order to withdraw funds through emergency withdraw.
3. Some times (ex: 30 days) later, administrator and operators begin to process withdraw requests again.
Since long time passes and price may changes a lot, the user may have slippage loss this time.

## Impact
Users who try to emergency withdraw funds have to set request deadline to be later than emergency withdraw delay.
So they may have slippage loss in the case that emergency withdraw delay is long.

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L384

## Tool used

Manual Review

## Recommendation
Modify `Vault.sol#emergencyWithdraw` function as follows.
```solidity
    function emergencyWithdraw(
        uint256[] memory minAmounts,
        uint256 deadline
    )
        external
        nonReentrant
        checkDeadline(deadline)
        returns (uint256[] memory actualAmounts)
    {
        uint256 timestamp = block.timestamp;
        address sender = msg.sender;
        if (!_pendingWithdrawers.contains(sender)) revert InvalidState();
        WithdrawalRequest memory request = _withdrawalRequest[sender];
--      if (timestamp > request.deadline) {
--          _cancelWithdrawalRequest(sender);
--          return actualAmounts;
--      }

        if (
            request.timestamp + configurator.emergencyWithdrawalDelay() >
            timestamp
        ) revert InvalidState();
    }
```
Since `emergencyWithdraw` function already have slippage control through `minAmounts` and `deadline` parameter, `L384-L386` is not neccessary.
On the other hand, if the user wants to cancel withdraw request, he/she can call the `cancelWithdrawalRequest` function directly.

Duplicate of #57

**Comment by debugging3** [comment]
Escalate
I think this issue should be fixed because the user who set the deadline shorter than emergencyWithdrawalDelay can't emergency withdraw at all and in general the emergencyWithdrawalDelay is too long (ex: 90 days).
It means that the emergencyWithdraw function is totally useless unless fixed.

**Comment by sherlock-admin3** [comment]
> Escalate
> I think this issue should be fixed because the user who set the deadline shorter than emergencyWithdrawalDelay can't emergency withdraw at all and in general the emergencyWithdrawalDelay is too long (ex: 90 days).
> It means that the emergencyWithdraw function is totally useless unless fixed.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xHuntoor** [comment]
user mistakes are not considered valid due to sherlock rules

**Comment by debugging3** [comment]
It is not the user's mistake. Read the original issue more carefully.

At first, the request.deadline parameter should be short because it is used to prevent slippage.
Secondly, the emergencyWithdraw() requires the request.deadline to be longer than emergencyWithdrawDelay(90 days).
Thus the second contradicts the first condition.
 
Thus, the emergencyWithdraw() might never be used.

**Comment by z3s** [comment]
Hey, @debugging3 I think it works as intended, for example protocol handles withdraws normally, and users can set their desired deadlines, and suddenly the protocol stops processing withdraws, so it's the correct behavior that `emergencyWithdraw` check for specified deadline at first. and after that users can make new withdraw requests with long enough deadlines.

**Comment by debugging3** [comment]
Hi, @z3s. Please read the title and example scenario of the original issue once more.

At first, `emergencyWithdraw()` has no need of checking `request.deadline` because it is called by user himself and it has it's own parameters (`minAmounts`, `deadline`) for slippage control.
On the other hand, after a user register withdraw with long deadline, a long time ( < `emergencyWithdrawDelay`) passed, if the protocol resume processing withdraws, then the user's request may be processed normally but with slippage loss.

After all, the user who try to emergency withdraw must bear huge slippage loss and thus users will not use emergency withdraw at all.

**Comment by debugging3** [comment]
Duplicate of #270

**Comment by WangSecurity** [comment]
But the `emergencyWithdraw` has sufficient slippage protection, how they can suffer slippage loss if they input the desired `minAmounts`?

**Comment by debugging3** [comment]
Hi, @WangSecurity. Maybe you have a little misunderstand the key point of this issue. Users may suffer slippage loss in `processWithdrawals()` not in `emergencyWithdraw()`.

Possible Scenario:
1. For some reason, the protocol stopped processing withdrawals for a long time because of some problems.
2. A user have to `registerWithdrawal()` with `requestDeadline` > `emergencyWithdrawalDelay`(ex: 90 days) in order to withdraw LRTs by `emergencyWithdraw()`.
3. After a bit long time (ex: 30 days) later, the protocol fixes the problems and resume processing withdrawals.
4. Therefore, the withdrawal request of the user will be processd by `processWithdrawals()` instead of `emergencyWithdraw()`. However, it was not intended by the user and the original intention of the user is to process the request by `emergencyWithdraw()`.
5. Since a long period (> 30 days) passed from registering, the price of LRT has changed too much and the user may have slippage loss in `processWithdrawals()`.

I hope this explanation helps you a bit.

**Comment by WangSecurity** [comment]
It's very strange that you say that the problem is in `processWithdrawals` and not in `emergencyWithdraw` even though the first is not mentioned in the report at all.

Either way, I see now what you mean. As you've said in the report `cancelWithdrawalRequest` the users can cancel their withdrawal request if they don't want to suffer the slippage loss and I believe setting the deadline for such time period is the design decision. Hence, it's up to the user to decide if they want to wait and have a risk of slippage loss or not and cancel the request.

Planning to reject the escalation and leave the issue as it is.

**Comment by debugging3** [comment]
> It's very strange that you say that the problem is in `processWithdrawals` and not in `emergencyWithdraw` even though the first is not mentioned in the report at all.
> 
> Either way, I see now what you mean. As you've said in the report `cancelWithdrawalRequest` the users can cancel their withdrawal request if they don't want to suffer the slippage loss and I believe setting the deadline for such time period is the design decision. Hence, it's up to the user to decide if they want to wait and have a risk of slippage loss or not and cancel the request.
> 
> Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #57

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [debugging3](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/26/#issuecomment-2227745873): rejected

**Comment by debugging3** [comment]
@WangSecurity 
> It's very strange that you say that the problem is in processWithdrawals and not in emergencyWithdraw even though the first is not mentioned in the report at all.

At first, the report mentioned the problem is in `processWithdrawals` as follows.
> Some times (ex: 30 days) later, administrator and operators begin to `process withdraw requests` again.
Since long time passes and price may changes a lot, the user may have slippage loss this time.

In the above, `process withdraw requests` means `processWithdrawals`.

> Either way, I see now what you mean. As you've said in the report cancelWithdrawalRequest the users can cancel their withdrawal request if they don't want to suffer the slippage loss and I believe setting the deadline for such time period is the design decision.

Secondly, the user can't cancel withdrawal by calling `cancelWithdrawalRequest` because the user can't know whether the protocol resume processing withdrawals or not.
And I can't believe setting deadline for 90 days long is the design decision because such a long deadline can't be used to avoid slippage.

**Comment by WangSecurity** [comment]
The decision remains, I still believe it's protocol's design.
