### ISSUE TITLE
Ironsidesec - Computing `actualAmounts` via target ratios based on token amounts is wrong.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#268]
Ironsidesec

High

# Computing `actualAmounts` via target ratios based on token amounts is wrong.

## Summary
Instead, it should be done based on the token amount's value. Properly rebalancing the vault according to the target ratios can only be done in the recommended way. Withdrawal ratios include the price calculation with ratios `ratiox96values` which should also be done to depositing `expected amounts`.

## Vulnerability Detail
There are 2 issues in this type of `ratio accounting on token amounts`, 1. price impact, 2. token decimals compatability.

But first let's see how perfect the withdrawal accounting is

1. currently there is a vault with 100 wstETH with 100e18 LP supply. And a user deposits 3 wstETH.
2. A new lst gets added as underlying , ex: ezETH. And now target ratios is 50-50. And user deposits 2 wstETH and 2 ezETH. Currently wstETH is 1.18 ETH and 1ezETH is 1.05 ETH price.
3. But, after a while and multiple deposits from others, he tries to withdraw his stake by burning all LP. So he should get 5 wsETH and 2 ezETH value worth 7.95 ETH.
4. But with current ratio at 50-50% target ratio and bit skewed prices, the calculation comes out as [3.58 wstETH, 3.58 ezETH] at their lp value worth 7.95 ETH.

So, the withdrawing amounts are correctly accounted according to target ratios, due to total lp value being distributed in ratios. But below examples in deposit shows, rebalancing deposited amounts towards target ratios is wrong.

1. Diff voltile prices of underlying tokens.
- Imagine a vault with wstETH and rETH with the same prices where each is 1.18x of ETH price. And vault is at 50-50 target ratios due to same prices when vault starts. 
- But suddenly next day, there were many slashings of rETH and also rETH in lending pools accrued bad debt, whatever event that might cause a >3% price dip. 
- Now a user comes with [1 wstETH, 1rETH] as amounts, as it is aligned with correct 50-50 target ratios, the expected amounts will also be [1 wstETH, 1rETH]. 
- But 50-50 target ratio means in TVL value, with a 5% dip the expected amounts should have been [0.95 wstETH, 1 rETH] and remaining  0.05 wstETH should be sent back. 
- This is how you balance the vault according to the target ratios. But following token amount-based instead of value-based accounting will disbalance the vault and the target ratio cannot be matched. 
- The impact will rise if the volume of deposits are even high. This leads to going against the risk parameters set in the vault.

2. Different token decimals.
- Imagine a vault where one underlying token is wstETH with 18 decimals and another token with 6 decimals  at 50-50 target ratios is deposited as underlying, then the whole accounting is error-prone. 
- Imagine, the quote price is based on ETH value., To represent 1 ETH value in wstETH its 1e18, but for 6 decimals token its 1e6.
- Now a vault with 50% 18 decimal token A, and 50% token B with 6 decimals are used. And both are similar prices close to  1 ETH. So a user comes with 2 ETH worth of value abd 50% in each (1 wstETH and 1e6 of token B). 
- Now look at line 337 and line 352 below. The actual amounts that gets pulled will be [1e6, 1e6] instead of [1e18, 1e6]. 
- The ratios accounting is done on amounts but not on token values based on price and decimals.

https://github.com/mellow-finance/mellow-lrt/blob/35b83a9e2a099e47ec99fc17acb1e653a70810ae/src/Vault.sol#L364-L409

```solidity
2024-06-mellow/mellow-lrt/src/Vault.sol

309:     function deposit(
... SNIP ...
319:     {
... SNIP ...
333: 
334:         uint256 ratioX96 = type(uint256).max;
335:         for (uint256 i = 0; i < tokens.length; i++) {
336:             if (ratiosX96[i] == 0) continue; 
337:    >>>      uint256 ratioX96_ = FullMath.mulDiv(amounts[i], Q96, ratiosX96[i]);
338:             if (ratioX96_ < ratioX96) ratioX96 = ratioX96_;
339:         }
340:         if (ratioX96 == 0) revert ValueZero();
... SNIP ...
346:         for (uint256 i = 0; i < tokens.length; i++) {
347:             uint256 priceX96 = priceOracle.priceX96(address(this), tokens[i]);
348:             totalValue += totalAmounts[i] == 0
349:                 ? 0
350:                 : FullMath.mulDivRoundingUp(totalAmounts[i], priceX96, Q96);
351:             if (ratiosX96[i] == 0) continue;
352:    >>>      uint256 amount = FullMath.mulDiv(ratioX96, ratiosX96[i], Q96);
353:             IERC20(tokens[i]).safeTransferFrom( 
354:                 msg.sender,
355:                 address(this),
356:                 amount
357:             );
358:             actualAmounts[i] = amount;
359:             depositValue += FullMath.mulDiv(amount, priceX96, Q96);
360:         }
... SNIP ...
368:     }

```

## Impact
Following token amount-based ratio accounting instead of value-based accounting will disbalance the vault and the target ratio cannot be matched. The impact will rise if the volume of deposits are even high and vault with >= 2 volatile underlying token. This leads to going against the risk parameters set in the vault. Also tokens with != 18 decimals will get wrongly impacted in accounting, though token being low decimals has low likelihood.

Likelihood : medium because, token should be volatile and should have mutiple underlying tokens.

## Code Snippet
https://github.com/mellow-finance/mellow-lrt/blob/35b83a9e2a099e47ec99fc17acb1e653a70810ae/src/Vault.sol#L364-L409

## Tool used
Manual Review

## Recommendation
Do value-based target ratio accounting, not amounts-based. Properly rebalancing the vault according to the target ratios can only be done the recommended way.

**Comment by IronsideSec** [comment]
Escalate

> Following token amount-based ratio accounting instead of value-based accounting will disbalance the vault and the target ratio cannot be matched. The impact will rise if the volume of deposits are even high and vault with >= 2 volatile underlying token. This leads to going against the risk parameters set in the vault. Also tokens with != 18 decimals will get wrongly impacted in accounting, though token being low decimals has low likelihood.

> Likelihood : medium because, token should be volatile and should have mutiple underlying tokens.

Issue is being ignored due to current live protocol supporting only 1 underlying token
Issue is a valid medium when vault with >= 2 volatile underlying token, breaking proctocol rebalancing functionality according to set weights due to amount based accounting in deposit, instead of value based like in withdrawal.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> > Following token amount-based ratio accounting instead of value-based accounting will disbalance the vault and the target ratio cannot be matched. The impact will rise if the volume of deposits are even high and vault with >= 2 volatile underlying token. This leads to going against the risk parameters set in the vault. Also tokens with != 18 decimals will get wrongly impacted in accounting, though token being low decimals has low likelihood.
> 
> > Likelihood : medium because, token should be volatile and should have mutiple underlying tokens.
> 
> Issue is being ignored due to current live protocol supporting only 1 underlying token
> Issue is a valid medium when vault with >= 2 volatile underlying token, breaking proctocol rebalancing functionality according to set weights due to amount based accounting in deposit, instead of value based like in withdrawal.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Could you help me understand, the protocol is looking to have vaults with 2 underlying tokens? Is it documented? Or where does this assumption comes from?

**Comment by IronsideSec** [comment]
code in Vault.sol allows to have multiple underlying tokens. 
https://github.com/mellow-finance/mellow-lrt/blob/35b83a9e2a099e47ec99fc17acb1e653a70810ae/src/Vault.sol#L26
https://github.com/mellow-finance/mellow-lrt/blob/35b83a9e2a099e47ec99fc17acb1e653a70810ae/src/Vault.sol#L215
https://github.com/mellow-finance/mellow-lrt/blob/35b83a9e2a099e47ec99fc17acb1e653a70810ae/src/Vault.sol#L181-L182

Also there is  `ManagedRatiosOracle` contract that provides ratio management for underlying tokens within a vault. It allows updating and retrieving target ratios for the vault's assets using a 96-bit fixed-point precision system.
https://docs.mellow.finance/mellow-lrt-primitive/lrt-contracts/oracles/managedratiosoracle#overview

And they are implemnted in accounting of shares and amountOut on deposit and withdraw.
https://github.com/mellow-finance/mellow-lrt/blob/35b83a9e2a099e47ec99fc17acb1e653a70810ae/src/Vault.sol#L300-L309
https://github.com/mellow-finance/mellow-lrt/blob/35b83a9e2a099e47ec99fc17acb1e653a70810ae/src/Vault.sol#L480-L488

**Comment by 0xHuntoor** [comment]
for first problem
> This is how you balance the vault according to the target ratios. But following token amount-based instead of value-based accounting will disbalance the vault and the target ratio cannot be matched.

isn't this a design recommendation for sub-optimal design?

- Under the hood  rETH will always be converted to larger ETH (always its underlying shares positive rebase and never negative rebase)
- when ever a slashing happen in rETH then the slashed amount comes from the decentralised validator  and never comes from pooled ETH in their protocol (see rocketPool docs for reference)

for second problem, this would be grouped with this issue then #160

**Comment by IronsideSec** [comment]
@IlIlHunterlIlI
> Under the hood rETH will always be converted to larger ETH (always its underlying shares positive rebase and never negative rebase)
> when ever a slashing happen in rETH then the slashed amount comes from the decentralised validator and never comes from pooled ETH in their protocol (see rocketPool docs for reference)

For example, 
1. Me as a vault manager want to have  50% value in rETH and 50% in WETH  . Because that is my risk recommendation for my stakers. Imagine currently (50 rETH and 50 WETH balance making vault's value 100 ETH) and suddenly rETH fell off 10% like ezETH recently (may be overleveraged lending/ slashed whatever reason). 
2. Now vault's value is 95 ETH (50 ETH + 45ETH worth rETH). but still the amounts are 50 reth and 50 weth, only the value of reth dipped.  Now the deposits should move towards  coverting 50 eth into 47.5 eth and  50 reth amounts will become 53 reth so the vault will get rebalanced into 47.5 + 47.5 = 95 eth in terms of value, and amounts become 47.5 weth + 53 rETH balance.

This way of rebalancing happens  in my recommended way, an optimal way. Current mplemntation will treat 50 reth == 50 eth and doesn't care about its value during deposits. Its sub optimal, imo. 

second problem can be grouped with issue #160, still this issue's recommendation will fix #160 too because accounting is done on value , not low decimal amounts. 
But first problem here is more vital because of target weights are important risk parameters, and vault should follow it.

**Comment by 0xHuntoor** [comment]
> This way of rebalancing happens in my recommended way, an optimal way. Current mplemntation will treat 50 reth == 50 eth and doesn't care about its value during deposits. Its sub optimal, imo.

do we have sub-optimal designs to be valid issues?

> Me as a vault manager want to have 50% value

ye but can we confirm that the sponsor wants the same?

**Comment by IronsideSec** [comment]
so, you want to put stakers at risk ? As a user, seeing the vault with 50% each token he stakes. If one of the token moves down, it cant be rebalanced to 50% in value again due to wrong design. And my recommended design that rebalances properly is sub optimal ?? 

>do we have sub-optimal designs to be valid issues?

I am saying my recommended design is optimal. The design decision you talk about cannot rebalance acc. to the set token weights in a $50M+ tvl  vault. You keep repeating optimal/ sub optimal and their validity. I am saying the current design itself is wrong, not just sub optimal.

**Comment by WangSecurity** [comment]
Based on the statement inside known issues, I believe the scenario about different token decimals is not viable, since it's known there's an issue using tokens with different token decimals. But I believe the scenario "Diff volatile prices of underlying tokens" is correct. The protocol indeed looks into working with 2 underlying tokens and this report shows how it would cause an issue.

Planning to accept the escalation and validate with medium severity. Are there any duplicates?

**Comment by IronsideSec** [comment]
Coudn't find any. 
Searched  issues mentioning `actualAmount` => https://github.com/search?q=repo%3Asherlock-audit%2F2024-06-mellow-judging+actualAmounts&type=issues

**Comment by 10xhash** [comment]
> Based on the statement inside known issues, I believe the scenario about different token decimals is not viable, since it's known there's an issue using tokens with different token decimals. But I believe the scenario "Diff volatile prices of underlying tokens" is correct. The protocol indeed looks into working with 2 underlying tokens and this report shows how it would cause an issue.
> 
> Planning to accept the escalation and validate with medium severity. Are there any duplicates?

What issue is being caused here? Using token based deposits is perfectly valid. The intent of the project needs to be considered. If the project wanted the balances of the vault to be 50%-50% in value they wouldn't have been keeping the amount based deposits. In the StakingModule example, the vault want deposits to be 100% in weth while the withdrawals will be fully in stETH. They are not looking to rebalance based on value here

**Comment by IronsideSec** [comment]
> What issue is being caused here? Using token based deposits is perfectly valid. 

Invalid in these type of [vaults](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/268#issuecomment-2235713234) and why is also explained

> The intent of the project needs to be considered. If the project wanted the balances of the vault to be 50%-50% in value they wouldn't have been keeping the amount based deposits. In the StakingModule example, the vault want deposits to be 100% in weth while the withdrawals will be fully in stETH. They are not looking to rebalance based on value here

Your points are valid to the current vaults where 100% of the token ratio goes to one token. ex: WETH. But invalid for a vault that accepts (50% ezETH + 50% WETH ). Mellow is kind of Balancer of LRT ecosystem, where combo % of vault tokens are accepted on deposits and allocate to lrt protocols according to their risk parameter (i.e target ratio). The name `target ratio` says move the vaults funds to that ratios, but you can't due to token amounts accounting.

My issue raised here is, vault is listed with 50, 100 mil at risk param 50-50 in each, an volatile event will make vault rebanacing back to 50-50 in value is not possibe due to token amounts based accounting. 
Target ratios is a key important feature in these vaults and stakers deposit seeing the % of their funds allocated in set token ratios. And failing to keep up the vault in that ratio  is high mpact. But currently the mellow vaults are with 100% token ratio to one token. But  vaults with multiple tokens % is a valid likelihood. so saying `The intent of the project needs to be considered` is invalid.

**Comment by 10xhash** [comment]
> > What issue is being caused here? Using token based deposits is perfectly valid.
> 
> Invalid in these type of [vaults](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/268#issuecomment-2235713234) and why is also explained
> 
> > The intent of the project needs to be considered. If the project wanted the balances of the vault to be 50%-50% in value they wouldn't have been keeping the amount based deposits. In the StakingModule example, the vault want deposits to be 100% in weth while the withdrawals will be fully in stETH. They are not looking to rebalance based on value here
> 
> Your points are valid to the current vaults where 100% of the token ratio goes to one token. ex: WETH. But invalid for a vault that accepts (50% ezETH + 50% WETH ). Mellow is kind of Balancer of LRT ecosystem, where combo % of vault tokens are accepted on deposits and allocate to lrt protocols according to their risk parameter (i.e target ratio). The name `target ratio` says move the vaults funds to that ratios, but you can't due to token amounts accounting.
> 
> My issue raised here is, vault is listed with 50, 100 mil at risk param 50-50 in each, an volatile event will make vault rebanacing back to 50-50 in value is not possibe due to token amounts based accounting. Target ratios is a key important feature in these vaults and stakers deposit seeing the % of their funds allocated in set token ratios. And failing to keep up the vault in that ratio is high mpact. But currently the mellow vaults are with 100% token ratio to one token. But vaults with multiple tokens % is a valid likelihood. so saying `The intent of the project needs to be considered` is invalid.

`Me as a vault manager want to have 50% value in rETH and 50% in WETH` and `an volatile event will make vault rebanacing back to 50-50 in value is not possibe` : You can't and are not supposed to be able to with this implementation. It is up to the team how they want to design the protocol. You are insisting that the vault should maintain the target ratio in value. While the team wants and is using the target ratio to define the ratio in which the deposits are to be made (in token amounts)

`Target ratios is a key important feature in these vaults and stakers deposit seeing the % of their funds allocated in set token ratios`: Again, user's are not supposed to think their funds are maintained in the % of deposit ratios (in value) if the protocol is explicitly designed with a different behavior

If the deposit ratio is 50-50, and the price of token A is 1 and token B is 2, users are depositing itself in 1:2 value (it doesn't need any price drop etc. to see the difference of value vs token amounts). The vault and the user's are not expecting the value to be in the deposit target ratios

**Comment by IronsideSec** [comment]
> You can't and are not supposed to be able to with this implementation. It is up to the team how they want to design the protocol. You are insisting that the vault should maintain the target ratio in value. While the team wants and is using the target ratio to define the ratio in which the deposits are to be made (in token amounts)

`It is up to the team how they want to design the protocol`, ser current design allows vaults like 50-50, and depositing into them also works except the vault balancing towards token ratios. My recommended change (token value accounting) solves this.  
Current implementation maintains target ratios for token amounts and not token values. `It is up to the team how they want to design the protocol.`, yeah when they launch [these](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/268#issuecomment-2235713234) kind of vaults, they are in trouble for not maintaining the vault to set token ratios. What is the point of even applying token ratios to token amounts ?? why would the team even implement this parameter? It is good only if underlying tokens are 1: 1 price. If one of them is volatile and moves, then upcoming deposits cannot move to the set token ratios because the vault treats token amounts in ratios, instead of their value.



> If the deposit ratio is 50-50, and the price of token A is 1 and token B is 2, users are depositing itself in 1:2 value (it doesn't need any price drop etc. to see the difference of value vs token amounts). 

You have clearly explained the issue and fix. `The price of token A is 1 and token B is 2, users are depositing itself in 1:2 value`.  if the amount of tokens in vault are 100 : 100 each, then vault is in 1:2 in value.  If vault is  is deemed to be 50-50, then the token amounts would be in 100 : 50  and it will be 1:1 now, not 1:2 as you said. This is the issue I am pointing. Depositing in amounts as target ratios can't keep with the set ratios as the price changes. Token value-based target ratio accounting solves this.


> Again, user's are not supposed to think their funds are maintained in the % of deposit ratios (in value) if the protocol is explicitly designed with a different behavior
> The vault and the user's are not expecting the value to be in the deposit target ratios

Wdym `user's are not supposed to think their funds are maintained in the % of deposit ratios (in value)`.  The defi users exactly want their deposits in set risk and vault's funds in the target ratios set. As a user if I deposit 1$ in a 50-50 vault supporting renzo and kelp. Then I always need half of it exposed to each regardless of the price changes. The token amounts accounting doesn't care about price at all, this doesn't make the vault move toward target ratios when deposits are done.  

@10xhash  You are saying users should not expect to maintain 50%-50%, or rebalancing the value to token ratios. And this is also the intention of team's design.
But the LRT's biggest risk is exposure. That is why token ratios are set. only % of vault should be exposed to certain LRT protocol and vault should always keep up and maintain it. Token amounts cannot.

**Comment by WangSecurity** [comment]
After confirming with the sponsor, indeed @10xhash is correct and the current behaviour works exactly as intended. These target ratios are intended for the deposits in token amounts and they're not intended to be maintained inside the vault in value after the deposit.

Hence, the protocol work as expected and this report is only a recommendation to change the current design. Planning to reject the escalation and leave the issue as it is.

**Comment by IronsideSec** [comment]
@WangSecurity 
this issue also talks about`Different token decimals` like #160 
so dup with #160 if it becomes valid

**Comment by WangSecurity** [comment]
The decision was that underlying tokens with different decimals isn't a viable scenario, since the question about admin variable limitations is set to "No". Hence, we should assume the admins will use the values that won't cause any issues, i.e. setting underlying tokens with the same decimals.

Hence, the decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ironsidesec](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/268/#issuecomment-2232350047): rejected
