### ISSUE TITLE
X12 - WStethRatiosAggregatorV3 will not work properly if the base token is anything but stETH

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#29]
X12

Medium

# WStethRatiosAggregatorV3 will not work properly if the base token is anything but stETH

## Summary
Vaults have impermanent loss because they rely on the current price.

## Vulnerability Detail
The initial base token for our system is WETH, as seen [here](https://mellowprotocol.notion.site/Contracts-deployment-4cd6b91d9aef416291eb510d898f3841).

> baseTokens - Returns the base token associated with a specific vault. - baseTokens[Vault Address] = Wrapped ETH Address

With that in mind, when we extract the price from [WStethRatiosAggregatorV3](), our [latestRoundData](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/oracles/WStethRatiosAggregatorV3.sol#L19) will return `IWSteth(wsteth).getStETHByWstETH`, which is the price of `wstETH` in `stETH` terms based on [Lido's docs](https://docs.lido.fi/contracts/wsteth/#getstethbywsteth). 

However, `WETH : stETH` can have small price differences (i.e., it's not `1 : 1`), and the ratio of `wstETH` in `stETH` will result in slight price differences when used with our base token - `WETH`. This will cause the real price of `wstETH` to be over or undervalued, resulting in users depositing fewer or more shares than they should.

Note that even if the base token is something else (other than `stETH`), the same issue will appear.

## Impact
Slight price differences can cause inaccurate share allocations.

## Code Snippet
```solidity
function getAnswer() public view returns (int256) {
    return int256(IWSteth(wsteth).getStETHByWstETH(10 ** decimals));
}

function latestRoundData() public view override returns (uint80, int256, uint256, uint256, uint80) {
    return (0, getAnswer(), block.timestamp, block.timestamp, 0);
}
```

## Tool used
Manual Review

## Recommendation
Have [WStethRatiosAggregatorV3](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/oracles/WStethRatiosAggregatorV3.sol) perform another conversion for `stETH` to the base token and use that price.

Duplicate of #266

**Comment by z3s** [comment]
~~Invalid; `IWSteth(wsteth).getStETHByWstETH(10 ** decimals)` returns correct ratio!?~~

Edit: Ignore this comment

**Comment by ADK0010** [comment]
I think the above comment by @z3s is due to my report . I believe my report is under the name "Angry_Mustache_Man" has been wrongly duped with these set of issues . I don't know whether this family of issues are completely correct or not ,but the issue #228  I have submitted is wrong and for it the above comment by @z3s is valid .

**Comment by 0xHuntoor** [comment]
protocol in discord [**`we assume 1 steth == 1 weth, at least for current deployments`**](https://discord.com/channels/812037309376495636/1252276613417013353/1252980055546662912), does it implies on this?

**Comment by WangSecurity** [comment]
I see the comment from the sponsor, but the problem is that this issue can cause a loss of funds to users and this assumption is not mentioned in the README or code comments, I believe it should be valid and a duplicate of #266 as explained [here](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/266#issuecomment-2254171297)
