### ISSUE TITLE
X12 - Users can withdraw bellow `negativeAmounts` for a given token causing a complete DOS

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#52]
X12

High

# Users can withdraw bellow `negativeAmounts` for a given token causing a complete DOS

## Summary
[_calculateTvl](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L86) calculates the TVL by subtracting debt from the balance and will revert if the debt exceeds the balance. However, this check is not performed inside [emergencyWithdraw](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L371), allowing users to withdraw below the debt limit. This can brick the entire contract as [deposit](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L285), [emergencyWithdraw](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L371), and [processWithdrawals](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L536) will revert.

## Vulnerability Detail

**Where is the bug**

When [_calculateTvl](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L86) calculates the vault's TVL, it checks [_tvls](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L154) from every module. Some modules may return `data.isDebt` as `true`, making their returned amount a negative value.

```solidity
            for (uint256 j = 0; j < tokens.length; j++) {
                if (token != tokens[j]) continue;
                (data.isDebt ? negativeAmounts : amounts)[j] += amount;
                break;
            }
```

When the amount is negative, it is always subtracted from the positive one. If there are more `negativeAmounts` than `amounts` for a given token, the transaction will revert.

```solidity
        for (uint256 i = 0; i < tokens.length; i++) {
            if (amounts[i] < negativeAmounts[i]) revert InvalidState();
            amounts[i] -= negativeAmounts[i];
        }
```

**How the Bug Happens**

When users withdraw with [emergencyWithdraw](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L371), they withdraw the bond shares directly from the vault. There is a check verifying if the returned amount is `amounts[i] == 0`, but nothing verifies if our withdraw amount is bigger than the positive vault amount (token amount - debt).

```solidity
        // amounts is not checked if it's > than our withdraw amount
        (address[] memory tokens, uint256[] memory amounts) = baseTvl();

        if (minAmounts.length != tokens.length) revert InvalidLength();
        actualAmounts = new uint256[](tokens.length);
        for (uint256 i = 0; i < tokens.length; i++) {
            if (amounts[i] == 0) {
                if (minAmounts[i] != 0) revert InsufficientAmount();
                continue;
            }
```

Users can withdraw more tokens than the difference between `negativeAmounts` and `amounts`, either maliciously or accidentally, causing [_calculateTvl](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L86) to revert.

Example scenario:
- Debt for `tokenX` is really close to its amount, while other tokens have near 0 debt.
1. Withdraws happen as normal.
2. A user executes an [emergencyWithdraw](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L371), as their withdraw has not been included in the previous batches.
3. The withdrawal processes as normal, but it withdraws enough of `tokenX` shares that now it's `negativeAmounts > amounts`
4. Another user tries to deposit some tokens, but the transaction reverts because `_calculateTvl` determines that there are more `negativeAmounts` than `amounts` of `tokenX`.

**Note:**
Currently, [ManagedTvlModule](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/modules/erc20/ManagedTvlModule.sol) is the only one that can set custom debt. That debt can always be removed by an admin. However, an admin needs to intervene to prevent the vault from being completely bricked, which would mess up the internal accounting since the debt exists for a reason, creating a lose-lose situation.

## Impact
Vault DOS, user funds are stuck.

## Code Snippet
```solidity
            for (uint256 j = 0; j < tokens.length; j++) {
                if (token != tokens[j]) continue;
                (data.isDebt ? negativeAmounts : amounts)[j] += amount;
                break;
            }
```
## POC
Gist: https://gist.github.com/project-X12/cf3960455dbdd520fd0482d9ae1cf77d
Place inside: `mellow-lrt/tests/mainnet/unit/<name>.sol`
Run with: `forge test --fork-url <your url> --match-test test_POC_brick_vault -vvvv`

Result when we call `calculateStack`:

```jsx
    ├─ [26656] Vault::calculateStack() [staticcall]
      ... 
    │   ├─ [3678] ManagedTvlModule::tvl(Vault: [0xF62849F9A0B5Bf2913b396098F7c7019b51A820a]) [staticcall]
    │   │   └─ ← [Return] [Data({ token: 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, underlyingToken: 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, amount: 52250000004750000000 [5.225e19], underlyingAmount: 52250000004750000000 [5.225e19], isDebt: true })]
    │   └─ ← [Revert] InvalidState()
    └─ ← [Revert] InvalidState()
```

## Tool used
Manual Review

## Recommendation
Consider debt when processing withdrawals. The fix is simple - call [baseTvl](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L122) inside [emergencyWithdraw](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L371) and [underlyingTvl](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L112) inside [processWithdrawals](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L536). These functions will check if the debt is greater than the amounts and revert the withdrawal if so.

**Comment by 0x3b33** [comment]
Escalate

I disagree with the sponsor. 

There was no mention, either in the README or Discord, that `isDebt` will be `false` for all tokens. Given the current implementation, the vulnerability is likely to occur if `isDebt` is set to true for any token. We can assume that **`isDebt` is intended to be either `true` or `false`**, as there is a whole segment of code dedicated to handling such paths.

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L105-L108
```solidity
        for (uint256 i = 0; i < tokens.length; i++) {
            if (amounts[i] < negativeAmounts[i]) revert InvalidState();
            amounts[i] -= negativeAmounts[i];
        }
```

However, as described in the issue above, this handling is missed inside `emergencyWithdraw`. The debt part is not accounted for when users execute `emergencyWithdraw`, which leads to a state of **full DOS.**

Sherlock’s judging rules can be seen here (https://docs.sherlock.xyz/audits/judging/judging#v.-how-to-identify-a-medium-issue):

> V. How to identify a medium issue: Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed a small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

The issue meets Sherlock's requirement of at least Medium, as it causes a loss of funds but requires specific states.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I disagree with the sponsor. 
> 
> There was no mention, either in the README or Discord, that `isDebt` will be `false` for all tokens. Given the current implementation, the vulnerability is likely to occur if `isDebt` is set to true for any token. We can assume that **`isDebt` is intended to be either `true` or `false`**, as there is a whole segment of code dedicated to handling such paths.
> 
> https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L105-L108
> ```solidity
>         for (uint256 i = 0; i < tokens.length; i++) {
>             if (amounts[i] < negativeAmounts[i]) revert InvalidState();
>             amounts[i] -= negativeAmounts[i];
>         }
> ```
> 
> However, as described in the issue above, this handling is missed inside `emergencyWithdraw`. The debt part is not accounted for when users execute `emergencyWithdraw`, which leads to a state of **full DOS.**
> 
> Sherlock’s judging rules can be seen here (https://docs.sherlock.xyz/audits/judging/judging#v.-how-to-identify-a-medium-issue):
> 
> > V. How to identify a medium issue: Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed a small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.
> 
> The issue meets Sherlock's requirement of at least Medium, as it causes a loss of funds but requires specific states.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xklapouchy** [comment]
This issue is only valid if new TvlModule will be developed, and only if such module will be for debt accounting.

In the contest scope all TvlModules are non debt modules, all have isDebt flag as false and it can't be changed.

**Comment by blckhv** [comment]
The fact that `ManagedTvlModule` is in the scope of this audit and it has the ability to set isDebt to true makes this issue valid.

**Comment by mugarenko-hacken** [comment]
I agree to that.

**Comment by 0xklapouchy** [comment]
Agree.

**Comment by 0xklapouchy** [comment]
From all the duplicates the #258 is the only one pointing out the same path to the issue.

**Comment by WangSecurity** [comment]
I agree with the escalation and [this message](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/52#issuecomment-2230176532). Based on them, I believe the issue warrants medium severity. Planning to accept the escalation and validate with medium severity.

I see the duplicates #152, #226 and #258 are escalated as well, so will deal with them individually. If there are any more duplicates missing, please let me know.

**Comment by 0x3b33** [comment]
Just a note (prob. the issue number was mistyped) -  it's actually [258](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/258), not  [285](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/285).

**Comment by 10xhash** [comment]
> I agree with the escalation and [this message](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/52#issuecomment-2230176532). Based on them, I believe the issue warrants medium severity. Planning to accept the escalation and validate with medium severity.
> 
> I see the duplicates #152, #226 and #285 are escalated as well, so will deal with them individually. If there are any more duplicates missing, please let me know.

The admin is trusted with setting the values in ManagedTVLModule (ie. they can set it to any value and artificially increase/decrease the tvl of the vault to any extent without any constraints) and is expected to set it to reasonable values. This issue requires the admin to set debt (ie. this artificially reduces the balance of the vault while the vault still has even greater assets) to extremely high amounts which is not a reasonable scenario.

And even then, the DOS is not permanent as admin can reduce the debt and the system will be working again

**Comment by 0x3b33** [comment]
Yes the manager is the only one that can set the debt, however since such mechanics are implemented and the path for debt is handled (inside [_calculateTvl](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L105-L108) ) then this can be used.

However when used it will cause the vulnerability shown in the report. As stated in the report above the admins can remove the debt, however since it was put in place by them in the first place it means that it should be there until cleared or paid back.

> Note:
Currently, [ManagedTvlModule](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/modules/erc20/ManagedTvlModule.sol) is the only one that can set custom debt. That debt can always be removed by an admin. However, an admin needs to intervene to prevent the vault from being completely bricked, which would mess up the internal accounting since the debt exists for a reason, creating a lose-lose situation.

I also need to add that **if an admin is needed in order to clear a system wide DOS caused by the system operating normally**, then it is actually an issue.

**Comment by WangSecurity** [comment]
To clarify, by saying only the manager can set the debt you refer to manager setting `isDebt` flag to `true`, correct? @10xhash @0x3b33

**Comment by 0x3b33** [comment]
Yes, the manger/admin (not users) can set a custom debt (most likely if the protocol wants to take some money out for development or other reasons) using [setParams](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/modules/erc20/ManagedTvlModule.sol#L12) where he can set `isDebt` to `true` and the `amount` of debt that the system has take out. This can be done on 1 module or a few, if for example multiple tokens have been taken out as debt (wstETH, WETH...).

**Comment by WangSecurity** [comment]
Could you also help me which value is used in the deployment script? (I assume it's `false`, but want to verify)

**Comment by 0xklapouchy** [comment]
@WangSecurity 

ManagedTvlModule is not present in the deployment script (only import statement, but no deploy), and is not used in live contracts: https://docs.mellow.finance/mellow-lrt-primitive/contract-deployments

**Comment by 0x3b33** [comment]
@WangSecurity it's not currently used in the deploy scripts, however it's very well test inside our `VaultTest.sol`- https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/tests/mainnet/unit/VaultTest.t.sol#L1470 

I can also confirm (or show some screenshots if you want evidence) from sponsor chats that `isDebt` is will have another use (besides the above mentioned one) - for when an LST is slashed. 

Edit: It's also in the docs - https://docs.mellow.finance/mellow-lrt-primitive/lrt-contracts/modules/tvlmodules/managedtvlmodule#overview

> ManagedTvlModule contract provides a mechanism to artificially reduce or increase tvl using regular or debt tokens in the vault to reduce possible losses due to slashing events.

With that in mind, given that `ManagedTvlModule` is in scope, it's debt is handled [in other places of the code](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L105-L108) and that `ManagedTvlModule` is gonna be used I think it's gonna be enough to prove that a case where `isDebt == true` will likely happen.

**Comment by WangSecurity** [comment]
Based on the above comment, I agree that `isDebt` flag being true is a viable scenario. I understand we don't have any limitations on this value, but it's a boolean, so I believe it's fair to assume that either of values is possible, especially with a contextual evidence of it.

Hence, the decision remains the same, to validate the report with medium severity.

**Comment by WangSecurity** [comment]
Result:
Medium
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/52/#issuecomment-2228188699): accepted

**Comment by WangSecurity** [comment]
@0x3b33 additionally inspecting this issue, could you share the screenshots from the discussion with the sponsor?

**Comment by 0x3b33** [comment]
@WangSecurity I am tagging @blckhv (he is the one with the screenshots), for now I can link you to [Mellow docs](https://docs.mellow.finance/mellow-lrt-primitive/lrt-contracts/modules/tvlmodules/managedtvlmodule#overview) where they state that it's for **"to reduce possible losses due to slashing events."**

> ManagedTvlModule contract provides a mechanism to artificially reduce or increase tvl using regular or debt tokens in the vault to reduce possible losses due to slashing events.

**Comment by WangSecurity** [comment]
I've got the screenshot in Discord:
![image](https://github.com/user-attachments/assets/d6ce4751-988a-4f17-8b6e-87df483938eb)

Additionally considering this report, I see the following:
1. isDebt flag is set by the admin.
2. The debt amount is set by the admin.
3. The debt amount is decreased by the admin.
4. This module is managed only by the admin.

So the problem which is described in this report will be completely the admin's responsibility. Moreover, as I understand it's a design decision the protocol should stop functioning when `negativeAmounts > amounts` and the protocol shouldn't function until the admin resolves the debt. Additionally, the following rule should apply:
> An admin action can break certain assumptions about the functioning of the code. Example: Pausing collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.


Hence, I'm planning to revert my decision and invalidate this report.

**Comment by 0x3b33** [comment]
Hey @WangSecurity , I understand your way of thinking, and when you explain it like that, it can seem like it's an admin issue.

However, my report is not about `isDebt` and its values but about the fact that `processWithdrawals` handles debt perfectly and prevents users from leaving fewer assets than there is debt in the vault. But `emergencyWithdraw` doesn't, allowing users to withdraw most of the assets (even all), leaving the vault in a state where `negativeAmounts > amounts`. Because of this, users will DOS the whole vault, meaning there won't be any more withdrawals or even deposits, even though deposits will add assets, which will raise the vault assets above the debt.

A state where `negativeAmounts > amounts` is absolutely bad and probably unrecoverable. The admin can, of course, erase this value, but the actual assets missing, represented by this debt amount, **won't be in the vault.** 

Simply put, an **admin lowering the debt will mean that the vault reports having more assets than it actually has, preventing the last few users from leaving** (there won't be any assets left for them to withdraw). In both cases, the situation is not good.

**Comment by WangSecurity** [comment]
Fair points, but still the debt is managed by the admin and I see how this scenario is completely possible, if the admin just sets `isDebt` to true. In that case, there's a constantly growing debt, while the admin can manage it frequently changing the variable from true to false and vice versa, so debt doesn't constantly grow but is steadily paid out. Additionally, the following rule should apply since this entire scenario is dependant on the admin actions:

> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

I admit it was a mistake on my end to not apply it initially, but I believe it should be applied here and the issue should be invalid as it was.

**Comment by 0x3b33** [comment]
Yes, the debt is managed by the admin, but that's just a representation of the debt. The real debt exists inside the vault and isn't managed by any other mechanism. This is the only way they can manage share value decrease and actually report a loss to the vault.

In the case of debt occurring, let's say because of a slash, the admin is forced to report a debt. If they don't, the vault will show a higher share value than the real one, allowing the first users to withdraw more assets and leaving the last few stuck inside the vault. Here is an example with numbers to visualize it more clearly:

Example:
  
| *Prerequisites*        | *Values*    |
|------------------------|-------------|
| Vault base token       | WETH        |
| Vault asset            | wstETH      |
| wstETH price (in WETH) | 1.2         |
| Total assets           | 1000 wstETH |
| Vault LP               | 1200        |

There is a slash of 10% (big number to clearly show results + easy math), lowering `wstETH` price to 1.08:

1. If the admin doesn't report the debt, the price would still be 1.2, making `1 LP == 0.83 wstETH`. Users would be able to withdraw the whole 900 `wstETH` with just `0.83 * x = 900, x=1084.34` LP tokens, leaving the rest of the users (owning) `1200 - 1084.34 = 115.66` LP tokens stuck inside the vault, with no `wstETH` left to withdraw.

2. If the admin reports the bad debt, the new price would be 1.08, making 1 LP worth `900 / 1200 = 0.75`. This would allow users to withdraw their assets at their actual price.

Note that slashing doesn't need to be 10% or 20%; it can be just a few percentage points, and the admin would be forced to set the debt, or else users would be able to arbitrage the vault. This shows how an admin is forced to set the debt and keep it that way, lowering it slightly with every repayment.

**Comment by WangSecurity** [comment]
I understand and agree that setting the debt is a viable scenario. But even with numerical examples, I believe the admin is completely responsible for that debt and for the module to function appropriately. Even if it leads to such DOS scenario, where users' funds are stuck, the admin can lower the debt or set `isDebt` to false, so the vault can function. Yes, the users would lose their funds, but it falls under the following rule:

> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue

Hence, I still believe it should be invalid.

**Comment by 0x3b33** [comment]
> Yes, the users would lose their funds

It will cause direct loss of funds in a likely scenario.

> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue

The statement above falls under "Admin Input/call validation", however the issue has nothing to do with admin input/call validation. 

The report is not about validating any admin functions and the recommendation doesn't suggest any of that. It's about `emergencyWithdraw` lacking a mechanic to handle `isDebt` (unlike `processWithdrawals`). Before and after the fix the admin would be free to set that value to whatever it needs be. However, after the fix this issue will not occur.

**Comment by WangSecurity** [comment]
I still believe it falls down this rule, since the admin’s calls lead to user losing funds. Secondly, I believe it’s a fair decision to not allow users withdraw by themselves (i.e. through emergency withdrawal) in case the negative amounts exceed amounts, so it doesn’t lead to pool being insolvent and allows the admin to control it.

hence, the decision remains the same to invalidate the report.

**Comment by debugging3** [comment]
> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue

I understand admin's mistake could not be considered valid issue. But since setting debt of TVL module is not a mistake but a legitimate operation of admin, it is unfair that users  lose funds by this. 
If it is the design choice, then then the protocol should explain about this issue clearly in the docs, I think.

**Comment by 0x3b33** [comment]
>  I believe it’s a fair decision to not allow users withdraw by themselves

But that's what the whole report describes - users withdrawing more assets than there is debt and leaving the protocol insolvent.

>  so it doesn’t lead to pool being insolvent

But it does, the example states it very clearly

>  Users would be able to withdraw the whole 900 wstETH with just 0.83 * x = 900, x=1084.34 LP tokens, leaving the rest of the users (owning) 1200 - 1084.34 = 115.66 LP tokens stuck inside the vault, with no wstETH left to withdraw.

**Comment by WangSecurity** [comment]
> I understand admin's mistake could not be considered valid issue. But since setting debt of TVL module is not a mistake but a legitimate operation of admin, it is unfair that users lose funds by this.

I believe it was addressed above.

> If it is the design choice, then then the protocol should explain about this issue clearly in the docs, I think

The protocols are not obligated to explain each decision or the intended functionality of their code.

> But that's what the whole report describes - users withdrawing more assets than there is debt and leaving the protocol insolvent.

I'm sorry, it was poor phrasing from my side. I mean that when the protocol enters the state of `negativeAmounts > amounts`, it is intended to revert at this point, not to allow further debt growth, i.e. the protocol allows for the last withdrawal that would make `negativeAmounts > amounts` true and then stop processing `emergencyWithdrawal`s. 

Again, after further looking at this issue, I believe it's the admin's responsibility and it's their actions which lead to such a scenario. And their actions can resolve the issue if it comes up. Hence, I believe it should be invalid.

**Comment by 0x3b33** [comment]
> And their actions can resolve the issue if it comes up

This is not true as them removing the debt would cause another issue - insolvency (a much bigger one in fact). 

We've covered every point by now, and I am still unsure why it would be better suited as invalid rather than a valid one. However, it looks like you don't think leaving this issue as valid would be fair.

**Comment by WangSecurity** [comment]
> This is not true as them removing the debt would cause another issue - insolvency (a much bigger one in fact).

Yep, I see, but from my perspective it perfectly fits the rule of admin actions causing loss of funds to users, hence, invalid. I see your side and your arguments, but from my perspective this case fits the rule and should be invalid.

**Comment by 0x3b33** [comment]
I see you've already made up your mind about this issue. I can still argue that the admin has no power over the real assets, but that's already very well explained. Hopefully the above happens to the protocol some day, it would be a really good test to see if it's actually an issue or not. I will leave it with that, we've already said everything there is to be explained.

**Comment by debugging3** [comment]
> I'm sorry, it was poor phrasing from my side. I mean that when the protocol enters the state of negativeAmounts > amounts, it is intended to revert at this point, not to allow further debt growth, i.e. the protocol allows for the last withdrawal that would make negativeAmounts > amounts true and then stop processing emergencyWithdrawals.

I think `negativeAmounts > amounts` of only one TVL module doesn't mean directly the debt of the vault because the vault has several TVL modules and debt state of one of them is not equal to the total debt state of vault. Therefore, in such case, admin has no need of stopping emergencyWithdrawals.
That is, although one TVL module has debt, if others has profit and the profit covers debt, the state of vault is stable and there is no need for admin to do anything such as stopping some functions of the vault.

**Comment by WangSecurity** [comment]
I believe it still perfectly fits the rule of admin actions causing loss of funds to users. Hence, the decision remains the same.
