### ISSUE TITLE
xKeywordx - [H-2] - DoS attack to prevent the `processWithdrawals` call from the `SimpleDVTStakingStrategy` contract.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#76]
xKeywordx

High

# [H-2] - DoS attack to prevent the `processWithdrawals` call from the `SimpleDVTStakingStrategy` contract.

## Summary
The `SimpleDVTStakingStrategy::processWithdrawals` function will attempt to process the withdrawals of eligible users from the `Vault` contract. It will then convert the `wETH` token to `wstETH` token by calling the `StakingModule::convert` function, and in the end it will check the remaining `wstETH` balance of the `Vault` contract to see if the remaining `balance > maxAllowedRemainder`.

If the `balance > maxAllowedRemainder` then it will `revert LimitOverflow()`.

## Vulnerability Detail
A malicious user can see the `operator` calling the `SimpleDVTStakingStrategy::processWithdrawals` function and they can frontrun that transaction in order to transfer in an amount of `wstETH` tokens that will make the remaining `balance > maxAllowedRemainder` and this will make the transaction revert.

## Impact

Although the malicious user has no financial incentives to behave like this, they can still cause a potential DoS attack that will prevent the `operator` from [processing withdrawals](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/strategies/SimpleDVTStakingStrategy.sol#L83).

## Code Snippet

```solidity
    function processWithdrawals(...) external returns (bool[] memory statuses) {
//..
//..
        address wsteth = stakingModule.wsteth();
        uint256 balance = IERC20(wsteth).balanceOf(address(vault));
 //@audit | DoS by sending wsteth directly into the contract to increase its balance
        if (balance > maxAllowedRemainder) revert LimitOverflow();
    }
```

## Tool used

Manual Review

## Recommendation

Consider doing a "sweep" if the remaining `balance` is bigger than `maxAllowedRemainder` to prevent this from happening. This may not be the best fix, but it's an idea.

```diff
    function processWithdrawals(...) external returns (bool[] memory statuses) {
//..
//..
        address wsteth = stakingModule.wsteth();
        uint256 balance = IERC20(wsteth).balanceOf(address(vault));
+       if (balance > maxAllowedRemainder) {
+           uint256 remainder = balance - maxAllowedRemainder;
+           safeTransfer(address(vault), //some safe address, remainder );

}
    }
```

**Comment by 10xhash** [comment]
Escalate

This issue can occur without a donation or a malicious front run under normal operating scenarios. If user's are cancelling their withdrawal request/modifying their withdrawal lpAmount, then the entire tx could revert due to the check `balance > maxAllowedRemainder`

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue can occur without a donation or a malicious front run under normal operating scenarios. If user's are cancelling their withdrawal request/modifying their withdrawal lpAmount, then the entire tx could revert due to the check `balance > maxAllowedRemainder`

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
I agree with the escalation and the use of flashbots wasn't mentioned anywhere.

But the problem is that this issue causes only DOS of one block as I understand no lock of funds for >=7 days. On the other hand, the withdrawal requests have deadline checks, and this issue can cause withdrawal requests to pass, resulting in users submitting the new withdrawal request and waiting for the withdrawal. Hence, I believe it's indeed time-sensitive.

Planning to accept the escalation and validate the issue with medium severity, since it can only happen when the withdrawal is relatively near the `maxAllowedRemainder`.

**Comment by 0xHuntoor** [comment]
@WangSecurity only hash report identify the escalated comment

other reports just talks about donation attacks that will results in a big win for lp holders in the vault 

Second:
- this doesn't occur when the operator(trusted Role) chose not to stake any amounts
`if (amountForStake == 0) return vault.processWithdrawals(users);`

in the above check we immediately chose to process withdraw without getting to the check

```solidity
    function processWithdrawals(
        address[] memory users,
        uint256 amountForStake
    ) external returns (bool[] memory statuses) {
        _requireAtLeastOperator();
        if (users.length == 0) return statuses;
        emit ProcessWithdrawals(users, amountForStake, msg.sender);

@>>        if (amountForStake == 0) return vault.processWithdrawals(users);

        vault.delegateCall(
            address(stakingModule),
            abi.encodeWithSelector(
                IStakingModule.convert.selector,
                amountForStake
            )
        );

        statuses = vault.processWithdrawals(users);
        address wsteth = stakingModule.wsteth();
        uint256 balance = IERC20(wsteth).balanceOf(address(vault));
        if (balance > maxAllowedRemainder) revert LimitOverflow();
    }
```

just want to add that the scenario mentioned above from Hash only works when combining the `amountForStake` - amounts withdrawn + `IERC20(wsteth).balanceOf(address(vault))` > `maxAllowedRemainder`

plus withdraw in its core is not time sensitive totally (not a swap or liquidation like  situation), the following situation here is same like operator getting late from `processWithdrawals` by one Block due to him not being active

in fact this can happen and accepted from protocol **`Manager doesn't process withdrawals till emergency Delay`** here from readMe 

>If the Manager does not process the requests within the emergencyWithdrawalDelay period for any reason, the user can call the emergencyWithdraw function, which will withdraw the corresponding portion of tokens from the system

**Comment by WangSecurity** [comment]
Thanks for pointing out the incorrect duplicates. About this:

> in fact this can happen and accepted from protocol Manager doesn't process withdrawals till emergency Delay here from readMe

The deadline for withdrawals is always the the `emergencyWithdrawalDelay`? My assumption was that the user can set any deadline, but they can get to `emergencyWithdrawal` if they're deadline >= `emergencyWithdrawalDelay`, is it incorrect?

And about the check:
> just want to add that the scenario mentioned above from Hash only works when combining the amountForStake - amounts withdrawn + IERC20(wsteth).balanceOf(address(vault)) > maxAllowedRemainder

As I understand it's a viable scenario or it's impossible in reality based on how the protocol works?

**Comment by 0xHuntoor** [comment]
> The deadline for withdrawals is always the the emergencyWithdrawalDelay? My assumption was that the user can set any deadline, but they can get to emergencyWithdrawal if they're deadline >= emergencyWithdrawalDelay, is it incorrect?

this is correct, `deadline` is not forced to be >= `emergencyWithdrawalDelay`, so in fact user may put what ever they want, so they can put the `deadline` to be < `emergencyWithdrawalDelay` and they can withdraw then through `processWithdrawals()` and no way for them to call `emergencyWithdraw()`


> As I understand it's a viable scenario or it's impossible in reality based on how the protocol works?

yes its viable scenario as long as `amountForStake != 0`

**Comment by xKeywordx** [comment]
@WangSecurity @IlIlHunterlIlI may I understand why this is an incorrect duplicate? I think this is the first time I submitted something on Sherlock, and also the first time I get to see the judging process behind the scenes so please excuse me if my question is not appropriate.

I looked at 10xhash's issue, and indeed he is approaching it from a different angle, but isn't the root cause the same and that is manipulating the final balance of the contract so that the `processWithdrawals` function fails?

It seems to me that both findings identified the root cause. Also, the donation attacks that will result in a "big win for lp holders" can be just a couple of wei, so it's not that big of a win.

As per Sherlock's docs, in order to be credited a duplicate one must:

```
IX. Duplication rules:

- Identify the root cause

- Identify at least a Medium impact

- Identify a valid attack path or vulnerability path

- Fulfills other submission quality requirements (e.g. provides a PoC for categories that require one)

```

I think mine checks all 4 of these as the root cause is the fact that the balance of the contract can be manipulated in order to make the function revert. How you manipulate it, is a different story. You can do it via a donation attack, you can do it via canceling your withdrawal request, changing the withdrawal lp amount, etc.

**Comment by 0xHuntoor** [comment]
~Valid attack path~

**Comment by xKeywordx** [comment]
@IlIlHunterlIlI I don't see how this is not a valid attack path. I suggest reading all the comments again, carefully. Even the lead judge z3s said quote "Issue is valid Low/Info".
So the issue is valid, the problem that we are debating here is the severity of the finding, not its validity.

The "fix" provided by the protocol is that they will use high gas or flashbots, but the use of flashbots was not mentioned anywhere in the contest QA.

I'm afraid that your comments might've caused more harm than providing clarity here since @WangSecurity came to the conclusion that this is an invalid duplicate based on your comments.

Even 10xhash's escalation implies that it is a valid attack path

```
Escalate

This issue can occur without a donation or a malicious front run under normal operating scenarios. ....
```

The issue can occur without a donation means that it can EITHER occur through a donation or EITHER through another path, which 10xhash explains further in his own finding, a scenario which I did not cover as I didn't think it is necessary to prove the point. I think my finding proves the point and it is enough to be valid, and it is also a valid dup, and I think it should be a Medium, not a Low because users can miss the deadline if the DoS happens at the right time.

I kindly ask you to refrain from making any more comments, as I've seen that someone else also complained about them in the Discord chat for another finding.

**Comment by xKeywordx** [comment]
@10xhash @z3s Sorry for the tag gents, but it's my first time taking part in the judging phase of a contest and I don't know the drill yet. I have no idea if someone else randomly commenting on the findings and influencing the final decision is normal or not. I would like to hear your opinions about this, of course, when you get back to work Monday or whenever that is :)

**Comment by xKeywordx** [comment]
To add to the reason why I think this should be a Medium and not a Low is that the `processWithdrawals(...)` function is time-sensitive. It calls the `Vault::analyzeRequest` function to ensure that only requests that are within their deadline at the time of the call are processed successfully. So again, if executed at the right time, users can be forced to go beyond the deadline that they set.

**Comment by WangSecurity** [comment]
Upon further review, the decision is that `processWithdrawals` is not time-sensitive. In that case, I believe the issue doesn't qualify for DOS requirements, since no lock up for >= 7 days and the affected function is not time-sensitive.

Planning to reject the escalation and leave the issue as it is.

About @xKeywordx asking why it's not a duplicate, I don't see where I said here, that it's not a valid duplicate, I think you're mixing up with the blacklist issue.

**Comment by xKeywordx** [comment]
![Screenshot 2024-07-22 121851](https://github.com/user-attachments/assets/982ebeb3-81e0-4dc7-9a92-a875abc52cfb)


@WangSecurity you said it in a comment above. 

I looked at it a bit more over the weekend and I agree that the impact is minimized by the fact that you also have the `emergencyWithdraw` option which can be used in case you go beyond the set deadline.

**Comment by WangSecurity** [comment]
@xKeywordx oh I see, but I think it's a misunderstanding between us then. At that point I didn't claim that this report specifically is incorrect, but marked that I saw his comment about duplicates being incorrect, but didn't say which ones are and which ones aren't.

Anyway, I still stand on my previous decision. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [10xhash](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/76/#issuecomment-2231625817): rejected
